window.DRONLAB_A2_BLOQUE4_CASOS = {
  "curso": "DronLab A2",
  "bloque": "Bloque 4: Meteorologia aplicada a operaciones A2",
  "titulo": "Casos practicos Bloque 4 A2",
  "total": 12,
  "distribucion": {"baja": 5, "media": 5, "alta": 2},
  "casos": [
    {
      "id": "B4-CASO-001",
      "titulo": "Plaza con edificios altos y viento cruzado",
      "dificultad": "baja",
      "contexto": "Un piloto prepara la grabacion de un evento en una plaza rodeada de edificios altos.",
      "situacion_inicial": "La prevision general parece aceptable, pero en la plaza hay viento cruzado y posibles zonas de flujo irregular.",
      "informacion_disponible": ["La ingenieria cita este escenario como efecto rotor.", "Los edificios altos pueden alterar velocidad y direccion del viento.", "A2 se desarrolla en entornos urbanos o industriales complejos."],
      "problema_planteado": "Evaluar si la plaza puede tratarse como espacio abierto o si exige una evaluacion meteorologica local.",
      "preguntas_para_el_alumno": ["Que elementos del entorno condicionan el viento?", "Que riesgo meteorologico aparece?", "Que informacion falta para decidir Go/No-Go?"],
      "objetivos_de_aprendizaje": ["Reconocer turbulencia urbana.", "Relacionar obstaculos con viento local.", "Justificar una decision meteorologica previa."],
      "errores_habituales": ["Tratar la plaza como campo abierto.", "Confiar solo en la prevision general."],
      "conceptos_relacionados": ["Turbulencia urbana", "Efecto rotor", "Viento cruzado", "Go/No-Go"],
      "referencia_al_bloque": "Bloque 4 A2 - Escenarios reales implicitos"
    },
    {
      "id": "B4-CASO-002",
      "titulo": "Calle entre edificios paralelos",
      "dificultad": "baja",
      "contexto": "El piloto debe volar en una calle estrecha formada por dos edificios paralelos.",
      "situacion_inicial": "El viento circula entre los edificios y el piloto no sabe si aplicar la prevision media sin mas comprobaciones.",
      "informacion_disponible": ["La ingenieria pregunta como dos edificios paralelos influyen en la velocidad del viento.", "Los obstaculos afectan a direccion y velocidad del viento.", "El analisis de topografia es obligatorio para velocidad y direccion."],
      "problema_planteado": "Identificar que efecto local debe considerarse antes de despegar.",
      "preguntas_para_el_alumno": ["Que puede cambiar entre los edificios?", "Por que no basta el dato de viento medio?", "Que error de examen se evita?"],
      "objetivos_de_aprendizaje": ["Aplicar analisis de topografia.", "Interpretar efecto de obstaculos.", "Evitar responder solo sobre velocidad."],
      "errores_habituales": ["Pensar que el obstaculo solo reduce viento.", "No considerar cambios de direccion."],
      "conceptos_relacionados": ["Topografia", "Obstaculos", "Direccion del viento", "Velocidad del viento"],
      "referencia_al_bloque": "Bloque 4 A2 - Preguntas que nacen del bloque"
    },
    {
      "id": "B4-CASO-003",
      "titulo": "Buen tiempo en el suelo",
      "dificultad": "baja",
      "contexto": "Antes de iniciar una operacion, el piloto percibe aire calmo a nivel del suelo.",
      "situacion_inicial": "La zona tiene edificios y estructuras que pueden modificar el flujo en altura.",
      "informacion_disponible": ["La fuente advierte sobre confiar en buen tiempo en suelo.", "A 100 m los obstaculos pueden generar turbulencias severas.", "La consciencia situacional ambiental exige mirar mas alla de la sensacion en tierra."],
      "problema_planteado": "Determinar por que la sensacion en suelo no basta para declarar la operacion viable.",
      "preguntas_para_el_alumno": ["Que informacion esta usando el piloto?", "Que informacion falta?", "Que concepto puente ayuda a corregir el error?"],
      "objetivos_de_aprendizaje": ["Aplicar consciencia situacional ambiental.", "Distinguir aire en suelo y aire en altura.", "Evitar una decision basada en sensacion."],
      "errores_habituales": ["Confiar en el viento percibido en tierra.", "No observar obstaculos y altura."],
      "conceptos_relacionados": ["Consciencia situacional ambiental", "Turbulencia urbana", "Capas superiores", "Topografia urbana"],
      "referencia_al_bloque": "Bloque 4 A2 - Riesgos habituales"
    },
    {
      "id": "B4-CASO-004",
      "titulo": "Nubosidad que reduce visibilidad",
      "dificultad": "baja",
      "contexto": "Durante la preparacion de una mision, el piloto observa nubosidad que podria empeorar la visibilidad.",
      "situacion_inicial": "La operacion exige mantener VLOS y el piloto debe decidir si las condiciones visuales son suficientes.",
      "informacion_disponible": ["La formacion de nubes ayuda a identificar el estado de la atmosfera.", "La visibilidad VLOS depende de nubosidad y precipitaciones.", "El piloto debe abortar si no ve el dron con claridad."],
      "problema_planteado": "Relacionar nubosidad, VLOS y decision de continuidad.",
      "preguntas_para_el_alumno": ["Que condicion legal-operativa se compromete?", "Que debe observar el piloto?", "Que decision corresponde si no ve claro?"],
      "objetivos_de_aprendizaje": ["Relacionar nubes y VLOS.", "Aplicar prioridad de visibilidad.", "Evitar tratar nubes como teoria aislada."],
      "errores_habituales": ["Ignorar la perdida de visibilidad.", "Continuar por planificacion previa."],
      "conceptos_relacionados": ["Formacion de nubes", "VLOS", "Nubosidad", "Precipitaciones"],
      "referencia_al_bloque": "Bloque 4 A2 - VLOS y meteorologia"
    },
    {
      "id": "B4-CASO-005",
      "titulo": "Manual del UAS no consultado",
      "dificultad": "baja",
      "contexto": "El piloto prepara una operacion y conoce la prevision de viento, temperatura y humedad.",
      "situacion_inicial": "No ha consultado el manual del UAS C2 para comprobar los limites meteorologicos del fabricante.",
      "informacion_disponible": ["Los limites del fabricante incluyen viento maximo, temperatura y humedad.", "Mas alla de esos limites la seguridad no esta garantizada.", "Son el limite legal y tecnico del piloto."],
      "problema_planteado": "Identificar que comprobacion tecnica falta antes de decidir Go/No-Go.",
      "preguntas_para_el_alumno": ["Que documento debe consultar?", "Que tres umbrales cita la ingenieria?", "Por que no basta la experiencia del piloto?"],
      "objetivos_de_aprendizaje": ["Aplicar limites del fabricante.", "Relacionar manual y seguridad.", "Evitar inventar valores no presentes."],
      "errores_habituales": ["Usar limites genericos.", "Confiar en habilidad personal."],
      "conceptos_relacionados": ["Limites del fabricante", "Manual UAS C2", "Seguridad estructural", "Go/No-Go"],
      "referencia_al_bloque": "Bloque 4 A2 - Limites meteorologicos del fabricante"
    },
    {
      "id": "B4-CASO-006",
      "titulo": "Prevision antigua frente a condiciones actuales",
      "dificultad": "media",
      "contexto": "La prevision se consulto por la manana, pero la operacion se realiza varias horas despues.",
      "situacion_inicial": "Al llegar al lugar, las condiciones actuales parecen distintas a las previstas.",
      "informacion_disponible": ["La comprobacion meteorologica debe ser actual y para el momento de la operacion.", "Las condiciones actuales pueden diferir de la prevision realizada horas antes.", "La finalidad es decidir Go/No-Go antes del despliegue."],
      "problema_planteado": "Determinar como afecta una prevision antigua a la decision operativa.",
      "preguntas_para_el_alumno": ["Que informacion debe actualizarse?", "Que diferencia hay entre prediccion y condicion actual?", "Como se justifica la decision Go/No-Go?"],
      "objetivos_de_aprendizaje": ["Actualizar la evaluacion meteorologica.", "Separar prevision y realidad.", "Justificar decisiones con datos actuales."],
      "errores_habituales": ["Usar una prevision antigua.", "No reevaluar antes del despliegue."],
      "conceptos_relacionados": ["Evaluacion meteorologica", "Condiciones actuales", "Prevision", "Go/No-Go"],
      "referencia_al_bloque": "Bloque 4 A2 - Conceptos variables"
    },
    {
      "id": "B4-CASO-007",
      "titulo": "Rachas superiores al viento medio",
      "dificultad": "media",
      "contexto": "La prevision de viento medio parece compatible con la operacion.",
      "situacion_inicial": "En campo aparecen rachas que superan el viento medio previsto.",
      "informacion_disponible": ["Las rachas no son constantes.", "Pueden superar el viento medio previsto.", "El viento real debe cruzarse con limites del fabricante y viabilidad."],
      "problema_planteado": "Evitar que la decision se base solo en el promedio de viento.",
      "preguntas_para_el_alumno": ["Que dato puede ocultar el viento medio?", "Que debe revisarse si aparecen rachas?", "Que error se comete si se mantiene el plan inicial?"],
      "objetivos_de_aprendizaje": ["Interpretar rachas como variable critica.", "Relacionar viento real y manual.", "Reevaluar Go/No-Go."],
      "errores_habituales": ["Planificar solo con medias.", "Ignorar rachas por ser intermitentes."],
      "conceptos_relacionados": ["Rachas", "Viento medio", "Limites del fabricante", "Go/No-Go"],
      "referencia_al_bloque": "Bloque 4 A2 - Rachas de viento"
    },
    {
      "id": "B4-CASO-008",
      "titulo": "Niebla y sensores de vision",
      "dificultad": "media",
      "contexto": "El piloto se encuentra con humedad relativa muy alta y presencia de niebla ligera.",
      "situacion_inicial": "La visibilidad todavia parece suficiente, pero preocupa el comportamiento del UAS C2.",
      "informacion_disponible": ["La humedad muy alta puede condensar en sensores de vision.", "Puede provocar errores en el mantenimiento de posicion.", "La humedad tambien forma parte de los limites del fabricante."],
      "problema_planteado": "Analizar la niebla mas alla de la perdida de visibilidad.",
      "preguntas_para_el_alumno": ["Que riesgo afecta a sensores?", "Que limite debe comprobarse en el manual?", "Por que no basta evaluar solo VLOS?"],
      "objetivos_de_aprendizaje": ["Relacionar humedad y sensores.", "Aplicar limites del fabricante.", "Valorar posicionamiento del UAS."],
      "errores_habituales": ["Pensar que la niebla solo afecta a ver el dron.", "Ignorar condensacion en sensores."],
      "conceptos_relacionados": ["Humedad", "Sensores de vision", "Mantenimiento de posicion", "VLOS"],
      "referencia_al_bloque": "Bloque 4 A2 - Riesgos operacionales"
    },
    {
      "id": "B4-CASO-009",
      "titulo": "Panel solar con calor extremo",
      "dificultad": "media",
      "contexto": "Un piloto debe inspeccionar un panel solar en un dia de calor extremo.",
      "situacion_inicial": "No hay viento relevante, pero el calor puede afectar a la operacion.",
      "informacion_disponible": ["La ingenieria cita este escenario real implicito.", "El calor extremo puede afectar a la densidad del aire y refrigeracion de motores.", "El rendimiento de bateria depende de temperatura ambiente."],
      "problema_planteado": "Decidir que factores meteorologicos deben revisarse aunque el viento no sea problema.",
      "preguntas_para_el_alumno": ["Que efectos cita la fuente?", "Que rendimiento puede verse afectado?", "Que documento debe consultarse antes de decidir?"],
      "objetivos_de_aprendizaje": ["Relacionar temperatura y rendimiento.", "Aplicar limites del fabricante.", "Evitar centrar toda meteorologia en viento."],
      "errores_habituales": ["Decidir solo porque no hay viento.", "Olvidar temperatura y bateria."],
      "conceptos_relacionados": ["Temperatura", "Rendimiento de bateria", "Refrigeracion de motores", "Limites del fabricante"],
      "referencia_al_bloque": "Bloque 4 A2 - Escenario panel solar"
    },
    {
      "id": "B4-CASO-010",
      "titulo": "Checklist MEUH incompleto",
      "dificultad": "media",
      "contexto": "Un piloto revisa Entorno, UAS y Humano, pero omite la meteorologia.",
      "situacion_inicial": "La operacion parece preparada, aunque no se han comprobado viento local, VLOS ni limites meteorologicos.",
      "informacion_disponible": ["MEUH conecta categoria abierta y practica en campo.", "Sin verificar meteorologia, Entorno, UAS y Humano quedan comprometidos.", "La M es un estandar de verificacion previa."],
      "problema_planteado": "Detectar por que una revision aparentemente completa queda incompleta sin la M.",
      "preguntas_para_el_alumno": ["Que letra se ha omitido?", "Que pilares quedan comprometidos?", "Que comprobaciones meteorologicas faltan?"],
      "objetivos_de_aprendizaje": ["Aplicar MEUH como metodologia.", "Relacionar meteorologia con E/U/H.", "Evitar checklist mecanicos incompletos."],
      "errores_habituales": ["Recitar MEUH sin aplicar la M.", "Separar meteorologia de UAS y humano."],
      "conceptos_relacionados": ["MEUH", "Meteorologia", "Entorno", "UAS", "Humano"],
      "referencia_al_bloque": "Bloque 4 A2 - Conceptos puente"
    },
    {
      "id": "B4-CASO-011",
      "titulo": "Viento real supera el limite del manual",
      "dificultad": "alta",
      "contexto": "Durante una operacion, la telemetria o la observacion de campo indican viento real superior al limite indicado por el manual.",
      "situacion_inicial": "El piloto habia iniciado la operacion con una prevision aceptable, pero el dato real cambia.",
      "informacion_disponible": ["La pregunta nace del bloque.", "Los limites del fabricante son el limite legal y tecnico del piloto.", "Fuera de esos limites la seguridad no esta garantizada.", "Las condiciones actuales pueden diferir de la prevision."],
      "problema_planteado": "Razonar la respuesta sin inventar un procedimiento no incluido en la fuente.",
      "preguntas_para_el_alumno": ["Que dato tiene prioridad: prevision antigua o viento real?", "Que papel tiene el manual?", "Que no debe inventarse al resolver el caso?"],
      "objetivos_de_aprendizaje": ["Priorizar condiciones reales.", "Aplicar limites del fabricante.", "Evitar procedimientos no presentes en la ingenieria."],
      "errores_habituales": ["Continuar por la prevision inicial.", "Inventar maniobras no documentadas.", "Minimizar el limite del manual."],
      "conceptos_relacionados": ["Viento real", "Limites del fabricante", "Condiciones actuales", "Go/No-Go"],
      "referencia_al_bloque": "Bloque 4 A2 - Preguntas que nacen del bloque"
    },
    {
      "id": "B4-CASO-012",
      "titulo": "Decision meteorologica completa en entorno industrial",
      "dificultad": "alta",
      "contexto": "Un piloto planifica una operacion A2 en un entorno industrial con estructuras, calor, humedad y posible perdida de visibilidad.",
      "situacion_inicial": "La prevision general es favorable, pero el entorno presenta obstaculos, microclima local y condiciones que pueden afectar al UAS.",
      "informacion_disponible": ["El grafo empieza con consulta de prevision y MEUH.", "Los conceptos centrales son efectos locales, obstaculos y limites del fabricante.", "La aplicacion final es planificacion y decision Go/No-Go.", "VLOS debe mantenerse con claridad."],
      "problema_planteado": "Ordenar la evaluacion meteorologica completa antes de decidir la viabilidad.",
      "preguntas_para_el_alumno": ["Que debe comprobarse primero?", "Que factores locales alteran el viento?", "Que limites tecnicos deben cruzarse?", "Que condicion VLOS puede obligar a abortar?", "Como se justifica Go/No-Go?"],
      "objetivos_de_aprendizaje": ["Aplicar el grafo completo del bloque.", "Integrar entorno, UAS y meteorologia.", "Justificar una decision operacional sin contenido externo."],
      "errores_habituales": ["Decidir con un solo dato.", "Ignorar microclimas.", "Olvidar limites de fabricante.", "Desarrollar contenidos METAR/TAF fuera de alcance."],
      "conceptos_relacionados": ["Grafo de conocimiento", "MEUH", "VLOS", "Limites del fabricante", "Microclimas urbanos", "Go/No-Go"],
      "referencia_al_bloque": "Bloque 4 A2 - Sintesis y aplicacion"
    }
  ]
}
;
