window.DRONLAB_A2_BLOQUE6_PRACTICAS = {
  "curso": "DronLab A2",
  "bloque": "Bloque 6: Atenuaciones tecnicas y operacionales",
  "titulo": "Practicas guiadas Bloque 6 A2",
  "total": 10,
  "distribucion": {"baja": 4, "media": 4, "alta": 2},
  "practicas": [
    {
      "id": "B6-PRA-001",
      "titulo": "Tabla tecnica u operacional",
      "objetivo": "Clasificar medidas de mitigacion como atenuaciones tecnicas u operacionales.",
      "dificultad": "baja",
      "tiempo_estimado": "15 min",
      "material_necesario": ["Tabla de dos columnas", "Lista de medidas del bloque", "Ingenieria del Bloque 6"],
      "contexto": "La ingenieria marca como error de examen confundir atenuaciones tecnicas con operacionales.",
      "instrucciones_paso_a_paso": ["Crea dos columnas: tecnica y operacional.", "Situa en tecnica las funciones o dispositivos integrados en el UAS C2.", "Situa en operacional los procedimientos o maniobras ejecutados por el piloto.", "Incluye modo lento y margenes dinamicos en la columna correcta.", "Escribe una frase que explique el criterio usado."],
      "criterios_de_exito": ["Distingue hardware/software de maniobras/distancias.", "No mezcla funciones integradas con decisiones del piloto.", "Explica el criterio de clasificacion."],
      "errores_habituales": ["Llamar tecnica a cualquier medida de seguridad.", "Responder por intuicion.", "No mencionar al piloto en las operacionales."],
      "conceptos_relacionados": ["Atenuaciones tecnicas", "Atenuaciones operacionales", "Error de examen"],
      "referencia_al_bloque": "Bloque 6 A2 - Conceptos principales y riesgos"
    },
    {
      "id": "B6-PRA-002",
      "titulo": "Ficha de distancias A2",
      "objetivo": "Construir una ficha de memoria con distancias, modo lento y velocidad maxima.",
      "dificultad": "baja",
      "tiempo_estimado": "15 min",
      "material_necesario": ["Plantilla de datos criticos", "Boligrafo o editor", "Ingenieria del bloque"],
      "contexto": "El bloque contiene datos criticos de distancia horizontal normal, distancia en modo lento y velocidad maxima del modo lento.",
      "instrucciones_paso_a_paso": ["Escribe distancia horizontal A2 normal: >= 30 metros.", "Escribe distancia horizontal A2 modo lento: >= 5 metros.", "Escribe velocidad maxima modo lento: <= 3 m/s.", "Une 5 m con modo baja velocidad mediante una flecha.", "Anota el error que se evita al no usar 5 m como regla general."],
      "criterios_de_exito": ["Incluye 30 m, 5 m y <= 3 m/s.", "Relaciona 5 m con modo lento.", "No introduce otros valores."],
      "errores_habituales": ["Aplicar 5 m sin condicion.", "Olvidar <= 3 m/s.", "Confundir distancia y velocidad."],
      "conceptos_relacionados": ["30 metros", "5 metros", "Modo baja velocidad", "<= 3 m/s"],
      "referencia_al_bloque": "Bloque 6 A2 - Datos criticos"
    },
    {
      "id": "B6-PRA-003",
      "titulo": "Croquis de evaluacion del lugar",
      "objetivo": "Identificar en un croquis personas no participantes, obstaculos y zonas de prevencion.",
      "dificultad": "baja",
      "tiempo_estimado": "20 min",
      "material_necesario": ["Croquis vacio del entorno", "Marcadores", "Checklist de elementos minimos"],
      "contexto": "La evaluacion del riesgo relacionado con el lugar es un analisis previo del entorno de operacion.",
      "instrucciones_paso_a_paso": ["Dibuja el entorno de operacion.", "Marca personas no participantes potenciales.", "Marca obstaculos en tierra.", "Delimita zonas de prevencion de riesgos en tierra.", "Explica si el volumen operacional seria adecuado o que informacion faltaria."],
      "criterios_de_exito": ["Aparecen personas, obstaculos y zonas.", "La decision se vincula al volumen operacional.", "No se limita a dibujar la ruta del UAS."],
      "errores_habituales": ["Olvidar riesgo en tierra.", "No delimitar zonas.", "Evaluar sin informacion geografica."],
      "conceptos_relacionados": ["Evaluacion del lugar", "Personas no participantes", "Obstaculos", "Zonas de prevencion", "Volumen operacional"],
      "referencia_al_bloque": "Bloque 6 A2 - Evaluacion del riesgo del lugar"
    },
    {
      "id": "B6-PRA-004",
      "titulo": "Checklist antes del despegue",
      "objetivo": "Preparar una lista breve de comprobaciones vinculadas a las mitigaciones del Bloque 6.",
      "dificultad": "baja",
      "tiempo_estimado": "20 min",
      "material_necesario": ["Plantilla de checklist", "Datos criticos del bloque", "Escenario A2 simple"],
      "contexto": "La fuente indica configuracion correcta del software, actualizacion de datos geograficos y comprobacion obligatoria del sistema de terminacion antes del despegue.",
      "instrucciones_paso_a_paso": ["Incluye configuracion correcta del software del UAS C2.", "Incluye comprobacion del modo baja velocidad cuando proceda.", "Incluye actualizacion de datos geograficos de geoconsciencia.", "Incluye comprobacion del sistema de terminacion de vuelo.", "Relaciona cada item con el riesgo que reduce."],
      "criterios_de_exito": ["Los items proceden de la ingenieria.", "Cada comprobacion tiene finalidad clara.", "No se incluyen procedimientos no presentes como obligatorios."],
      "errores_habituales": ["Confiar en sistemas automaticos sin comprobar.", "Olvidar datos geograficos.", "Comprobar terminacion solo durante una emergencia."],
      "conceptos_relacionados": ["Configuracion de software", "Modo lento", "Geoconsciencia", "Sistema de terminacion"],
      "referencia_al_bloque": "Bloque 6 A2 - Dependencias y riesgos"
    },
    {
      "id": "B6-PRA-005",
      "titulo": "Aplicacion visual de la Regla 1:1",
      "objetivo": "Representar altura y distancia horizontal para aplicar la regla altura <= distancia horizontal.",
      "dificultad": "media",
      "tiempo_estimado": "20 min",
      "material_necesario": ["Plantilla con eje vertical y horizontal", "Escenario de calle comercial", "Datos criticos del bloque"],
      "contexto": "La ingenieria cita la realizacion de un video profesional en calle comercial manteniendo separacion minima y altura proporcional.",
      "instrucciones_paso_a_paso": ["Dibuja una persona no participante y la posicion del UAS.", "Marca la distancia horizontal.", "Marca la altura.", "Escribe la regla altura <= distancia horizontal.", "Justifica por que no basta con controlar solo una magnitud."],
      "criterios_de_exito": ["Altura y distancia aparecen juntas.", "La regla se escribe correctamente.", "La explicacion evita valores inventados."],
      "errores_habituales": ["Separar altura y distancia.", "Usar la regla como formula sin escenario.", "Inventar ejemplos numericos no dados si no son necesarios."],
      "conceptos_relacionados": ["Regla 1:1", "Altura proporcional", "Distancia horizontal", "Calle comercial"],
      "referencia_al_bloque": "Bloque 6 A2 - Datos criticos y escenarios"
    },
    {
      "id": "B6-PRA-006",
      "titulo": "Diseno de contencion con geofencing",
      "objetivo": "Relacionar geoconsciencia, geofencing y contencion del UAS en un escenario de inspeccion.",
      "dificultad": "media",
      "tiempo_estimado": "25 min",
      "material_necesario": ["Croquis de tejado y via publica", "Marcadores de limites", "Ficha de conceptos puente"],
      "contexto": "La fuente cita configuracion de un geo-caging virtual para inspeccionar un tejado sin que el dron vuele hacia la via publica colindante.",
      "instrucciones_paso_a_paso": ["Dibuja el tejado y la via publica colindante.", "Marca el volumen seguro definido.", "Dibuja el limite de geocaging/geofencing.", "Explica que conecta la geoconsciencia/geofencing.", "Indica que comprobacion relacionada con datos geograficos no debe olvidarse."],
      "criterios_de_exito": ["El limite virtual protege la via publica.", "Se relaciona planificacion y contencion.", "Se menciona el riesgo de datos geograficos obsoletos."],
      "errores_habituales": ["No delimitar el volumen seguro.", "Confiar en geofencing sin evaluar el lugar.", "Olvidar actualizacion de datos geograficos."],
      "conceptos_relacionados": ["Geoconsciencia", "Geofencing", "Geo-caging", "Contencion", "Datos geograficos"],
      "referencia_al_bloque": "Bloque 6 A2 - Conceptos puente y riesgos"
    },
    {
      "id": "B6-PRA-007",
      "titulo": "Gestion de entrada de terceros",
      "objetivo": "Justificar una decision operacional cuando una persona no participante entra en la zona de prevencion.",
      "dificultad": "media",
      "tiempo_estimado": "25 min",
      "material_necesario": ["Escenario con zona de prevencion", "Ficha de preguntas", "Croquis de posicion inicial y nueva posicion"],
      "contexto": "La ingenieria incluye la gestion de incursiones de terceros como aplicacion final del grafo de conocimiento.",
      "instrucciones_paso_a_paso": ["Marca la zona de prevencion inicial.", "Anade la entrada de una persona no participante.", "Describe que cambia en la exposicion al riesgo.", "Indica que familia de atenuaciones debe aplicarse.", "Redacta una justificacion sin inventar una maniobra concreta no presente."],
      "criterios_de_exito": ["La decision se basa en margenes dinamicos.", "Se identifica atenuacion operacional.", "Se evita continuar como si el entorno no hubiera cambiado."],
      "errores_habituales": ["Ignorar la entrada de terceros.", "Buscar una respuesta automatica no documentada.", "No justificar la decision."],
      "conceptos_relacionados": ["Personas no participantes", "Zona de prevencion", "Atenuaciones operacionales", "Margenes dinamicos"],
      "referencia_al_bloque": "Bloque 6 A2 - Aplicacion del grafo"
    },
    {
      "id": "B6-PRA-008",
      "titulo": "Recuperacion manual ante fallo",
      "objetivo": "Analizar una perdida de senal GPS desde el concepto de recuperacion manual.",
      "dificultad": "media",
      "tiempo_estimado": "25 min",
      "material_necesario": ["Escenario de perdida GPS", "Plantilla fallo-riesgo-control", "Lista de errores habituales"],
      "contexto": "La fuente cita perdida de senal GPS que obliga al piloto a reanudar control manual para evitar deriva hacia zona habitada.",
      "instrucciones_paso_a_paso": ["Lee el escenario de perdida GPS.", "Identifica que sistema automatico ha dejado de aportar seguridad.", "Relaciona recuperacion manual con control en riesgo imprevisto.", "Anota el error de confiar exclusivamente en automaticos.", "Redacta que conceptos del bloque usarias para justificar la respuesta."],
      "criterios_de_exito": ["Se identifica el riesgo imprevisto.", "Se menciona recuperacion manual.", "No se inventan procedimientos tecnicos de GPS."],
      "errores_habituales": ["Confiar exclusivamente en automaticos.", "No estar preparado para reanudar control manual.", "Desarrollar detalles tecnicos no presentes."],
      "conceptos_relacionados": ["Recuperacion manual", "Sistemas automaticos", "Perdida GPS", "Riesgo imprevisto"],
      "referencia_al_bloque": "Bloque 6 A2 - Riesgos y escenarios"
    },
    {
      "id": "B6-PRA-009",
      "titulo": "Auditoria A/B/C del Bloque 6",
      "objetivo": "Clasificar contenidos como imprescindibles, complementarios o fuera del alcance A2.",
      "dificultad": "alta",
      "tiempo_estimado": "30 min",
      "material_necesario": ["Tabla A/B/C", "Lista de conceptos mezclados", "Ingenieria del Bloque 6"],
      "contexto": "La auditoria del bloque distingue contenidos imprescindibles, complementarios y fuera de alcance.",
      "instrucciones_paso_a_paso": ["Coloca distancias 30m/5m, modo baja velocidad, geoconsciencia, limitacion de altura, Regla 1:1 y evaluacion del lugar en imprescindible.", "Coloca limitacion de energia de impacto y coordinacion tactica con observadores en complementario.", "Coloca SORA completa, EAS complejos y transpondedor modo S fuera de alcance.", "Justifica cada grupo con una frase.", "Revisa que no desarrollas el apartado fuera de alcance."],
      "criterios_de_exito": ["La clasificacion coincide con la auditoria.", "No se desarrolla SORA ni EAS complejo.", "Los contenidos imprescindibles quedan priorizados."],
      "errores_habituales": ["Desarrollar categoria especifica.", "Confundir complementario con imprescindible.", "Omitir datos criticos del bloque."],
      "conceptos_relacionados": ["Auditoria", "Imprescindible", "Complementario", "Fuera del alcance"],
      "referencia_al_bloque": "Bloque 6 A2 - Auditoria"
    },
    {
      "id": "B6-PRA-010",
      "titulo": "Plan integrado de mitigacion A2",
      "objetivo": "Integrar evaluacion del lugar, atenuaciones tecnicas, atenuaciones operacionales, contencion y recuperacion manual.",
      "dificultad": "alta",
      "tiempo_estimado": "35 min",
      "material_necesario": ["Caso integrador", "Croquis", "Checklist de datos criticos", "Tabla tecnica/operacional"],
      "contexto": "El grafo del bloque progresa desde personas no participantes y obstaculos hasta vuelo seguro en entornos complejos y gestion de incursiones de terceros.",
      "instrucciones_paso_a_paso": ["Identifica personas no participantes y obstaculos en el caso.", "Selecciona atenuaciones tecnicas presentes en la ingenieria.", "Selecciona atenuaciones operacionales aplicables.", "Incluye distancias 30m/5m, modo lento y Regla 1:1 cuando proceda.", "Anade contencion mediante geoconsciencia/geofencing y recuperacion manual como preparacion ante fallo.", "Redacta una decision final indicando que informacion falta si no puede decidirse."],
      "criterios_de_exito": ["Integra todas las capas del grafo.", "Usa datos criticos correctos.", "No introduce normativa externa ni contenidos fuera de alcance."],
      "errores_habituales": ["Usar solo una mitigacion aislada.", "Olvidar evaluar el lugar.", "Inventar requisitos no presentes.", "Desarrollar SORA completa."],
      "conceptos_relacionados": ["Grafo de conocimiento", "Evaluacion del lugar", "Atenuaciones tecnicas", "Atenuaciones operacionales", "Geoconsciencia", "Recuperacion manual"],
      "referencia_al_bloque": "Bloque 6 A2 - Integracion del bloque"
    }
  ]
}

