window.DRONLAB_A2_BLOQUE5_PRACTICAS = {
  "curso": "DronLab A2",
  "bloque": "Bloque 5: Rendimiento de Vuelo del UAS",
  "titulo": "Practicas guiadas Bloque 5 A2",
  "total": 10,
  "distribucion": {"baja": 4, "media": 4, "alta": 2},
  "practicas": [
    {
      "id": "B5-PRA-001",
      "titulo": "Mapa basico de fuerzas del UAS",
      "objetivo": "Identificar las cuatro fuerzas del vuelo y relacionarlas con estabilidad y maniobrabilidad.",
      "dificultad": "baja",
      "tiempo_estimado": "20 min",
      "material_necesario": ["Plantilla de UAS", "Marcadores de flechas", "Listado de conceptos del bloque"],
      "contexto": "El alumno debe comprender que sustentacion, peso, empuje y resistencia explican el equilibrio aerodinamico del UAS.",
      "instrucciones_paso_a_paso": ["Dibuja o usa una plantilla de UAS.", "Coloca las cuatro fuerzas alrededor del dron.", "Escribe una frase corta que explique la finalidad de cada fuerza.", "Relaciona el conjunto con estabilidad y maniobrabilidad.", "Senala que parte no debe desarrollarse con calculos avanzados."],
      "criterios_de_exito": ["Las cuatro fuerzas aparecen correctamente.", "El alumno relaciona fuerzas con vuelo controlado.", "No introduce formulas o datos no presentes en la ingenieria."],
      "errores_habituales": ["Confundir empuje con sustentacion.", "Olvidar resistencia.", "Convertir la practica en calculo teorico."],
      "conceptos_relacionados": ["Sustentacion", "Peso", "Empuje", "Resistencia", "Equilibrio aerodinamico"],
      "referencia_al_bloque": "Bloque 5 A2 - Fuerzas que actuan sobre el UAS"
    },
    {
      "id": "B5-PRA-002",
      "titulo": "Asociacion de ejes y movimientos",
      "objetivo": "Asociar correctamente eje longitudinal, lateral/transversal y vertical con roll, pitch y yaw.",
      "dificultad": "baja",
      "tiempo_estimado": "15 min",
      "material_necesario": ["Maqueta, dibujo o mano como referencia", "Tabla vacia de ejes", "Ficha de errores de examen"],
      "contexto": "La ingenieria cita como error de examen confundir movimientos de los ejes, especialmente asociar cabeceo al eje vertical.",
      "instrucciones_paso_a_paso": ["Dibuja los tres ejes cruzandose en el CG.", "Asocia longitudinal con alabeo/roll.", "Asocia lateral o transversal con cabeceo/pitch.", "Asocia vertical con guinada/yaw.", "Explica que error de examen evita esta asociacion."],
      "criterios_de_exito": ["Los tres ejes estan correctamente asociados.", "El CG aparece como punto de cruce.", "El alumno identifica el error de cabeceo/eje vertical."],
      "errores_habituales": ["Cruzar pitch y yaw.", "Olvidar que los ejes se cruzan en el CG.", "Aprender nombres sin movimiento."],
      "conceptos_relacionados": ["Eje longitudinal", "Eje lateral", "Eje vertical", "CG", "Roll", "Pitch", "Yaw"],
      "referencia_al_bloque": "Bloque 5 A2 - Ejes de Vuelo y Rotacion"
    },
    {
      "id": "B5-PRA-003",
      "titulo": "Ficha de datos criticos",
      "objetivo": "Construir una ficha de memoria con los datos criticos del Bloque 5.",
      "dificultad": "baja",
      "tiempo_estimado": "15 min",
      "material_necesario": ["Plantilla de datos criticos", "Ingenieria del bloque", "Boligrafo o editor"],
      "contexto": "El bloque contiene datos criticos de masa, altura, Indice K, asistencia barometrica y umbral de aprobado.",
      "instrucciones_paso_a_paso": ["Localiza los datos criticos en la fuente.", "Escribe Masa Maxima C2: < 4 kg.", "Escribe Altura Maxima AGL: 120 metros (400 ft).", "Escribe Indice K Planetario: < 4 para operar con seguridad.", "Anade asistencia barometrica y umbral de aprobado sin cambiar su formulacion."],
      "criterios_de_exito": ["Todos los valores aparecen con unidades o signos correctos.", "No se inventan datos adicionales.", "El alumno diferencia masa, altura, Indice K y aprobado."],
      "errores_habituales": ["Omitir el signo <.", "Olvidar AGL.", "Mezclar 75% con otros datos."],
      "conceptos_relacionados": ["MTOM", "Altura AGL", "Indice K", "Asistencia barometrica", "75%"],
      "referencia_al_bloque": "Bloque 5 A2 - Datos criticos"
    },
    {
      "id": "B5-PRA-004",
      "titulo": "Checklist de payload",
      "objetivo": "Preparar una comprobacion guiada de carga util antes de aceptar una configuracion.",
      "dificultad": "baja",
      "tiempo_estimado": "20 min",
      "material_necesario": ["Escenario con camara o sensor adicional", "Plantilla de checklist", "Tabla MTOM-CG"],
      "contexto": "La carga util conecta configuracion tecnica con rendimiento real y exige revisar MTOM y Centro de Gravedad.",
      "instrucciones_paso_a_paso": ["Lee el escenario de payload.", "Anota que elementos forman la masa total.", "Comprueba si la configuracion debe contrastarse con MTOM.", "Indica como podria afectar al CG.", "Redacta una decision provisional y que informacion faltaria."],
      "criterios_de_exito": ["El alumno incluye aeronave y carga en MTOM.", "El alumno analiza el CG.", "La decision no se basa solo en que el dron despegue."],
      "errores_habituales": ["Mirar solo fijacion fisica.", "Ignorar CG.", "Olvidar que payload afecta rendimiento real."],
      "conceptos_relacionados": ["Carga util", "Payload", "MTOM", "Centro de Gravedad", "Rendimiento real"],
      "referencia_al_bloque": "Bloque 5 A2 - Carga util"
    },
    {
      "id": "B5-PRA-005",
      "titulo": "Analisis de CG desplazado",
      "objetivo": "Evaluar consecuencias de un Centro de Gravedad desplazado por carga mal fijada.",
      "dificultad": "media",
      "tiempo_estimado": "25 min",
      "material_necesario": ["Dibujo de UAS con carga desplazada", "Ficha de riesgos", "Tabla de ejes"],
      "contexto": "Un CG desplazado puede hacer que el dron trabaje de forma asimetrica y agote prematuramente baterias o motores.",
      "instrucciones_paso_a_paso": ["Marca el CG teorico en el dibujo.", "Situa una carga desplazada.", "Describe como afecta al equilibrio.", "Relaciona el efecto con los tres ejes.", "Lista riesgos operacionales sin proponer solucion automatica."],
      "criterios_de_exito": ["El alumno identifica el desplazamiento del CG.", "Relaciona CG con control seguro en tres ejes.", "Reconoce agotamiento prematuro como riesgo."],
      "errores_habituales": ["Pensar que el mando compensa siempre.", "Confundir centro geometrico con CG.", "Ignorar bateria y motores."],
      "conceptos_relacionados": ["CG", "Estabilidad", "Tres ejes", "Baterias", "Motores"],
      "referencia_al_bloque": "Bloque 5 A2 - Riesgos operacionales"
    },
    {
      "id": "B5-PRA-006",
      "titulo": "Densidad del aire y rendimiento",
      "objetivo": "Relacionar altitud, temperatura y humedad con el rendimiento de las helices.",
      "dificultad": "media",
      "tiempo_estimado": "25 min",
      "material_necesario": ["Tres escenarios breves", "Plantilla causa-efecto", "Datos del bloque"],
      "contexto": "La densidad del aire cambia con altitud, temperatura y humedad y afecta directamente al rendimiento de las helices.",
      "instrucciones_paso_a_paso": ["Lee los tres escenarios: calor, gran altitud y humedad.", "Identifica que variable cambia en cada uno.", "Relaciona cada variable con densidad del aire.", "Explica como puede afectar a las helices.", "Indica que datos no puedes inventar si no aparecen en la fuente."],
      "criterios_de_exito": ["Se identifican altitud, temperatura y humedad.", "Se conecta densidad con helices.", "No se aportan valores no presentes en la ingenieria."],
      "errores_habituales": ["Responder solo bateria.", "Ignorar humedad.", "Inventar limites tecnicos."],
      "conceptos_relacionados": ["Densidad del aire", "Altitud", "Temperatura", "Humedad", "Helices"],
      "referencia_al_bloque": "Bloque 5 A2 - Conceptos variables"
    },
    {
      "id": "B5-PRA-007",
      "titulo": "Calibracion e instrumentos",
      "objetivo": "Construir una cadena de relacion entre sensores, ejes, estabilidad y trayectoria.",
      "dificultad": "media",
      "tiempo_estimado": "20 min",
      "material_necesario": ["Plantilla de cadena causal", "Listado de sensores citados", "Caso breve de trayectoria imprecisa"],
      "contexto": "Sensores mal calibrados, como IMU o brujula, distorsionan la percepcion del UAS sobre sus ejes de rotacion.",
      "instrucciones_paso_a_paso": ["Escribe IMU y brujula como sensores citados.", "Relaciona sensores con percepcion de ejes.", "Relaciona ejes con estabilidad.", "Relaciona estabilidad con trayectoria.", "Redacta dos preguntas que haria un profesor antes de continuar."],
      "criterios_de_exito": ["La cadena sensor-eje-estabilidad-trayectoria esta completa.", "No aparecen sensores inventados como eje principal.", "El alumno comprende la calibracion como puente."],
      "errores_habituales": ["Tratar calibracion como aviso menor.", "No conectar sensores con actitud.", "Confundir calibracion con MTOM."],
      "conceptos_relacionados": ["Calibracion", "IMU", "Brujula", "Ejes", "Estabilidad"],
      "referencia_al_bloque": "Bloque 5 A2 - Calibracion de instrumentos"
    },
    {
      "id": "B5-PRA-008",
      "titulo": "Autonomia real frente a autonomia prevista",
      "objetivo": "Evaluar como carga util y resistencia al viento modifican la autonomia de bateria.",
      "dificultad": "media",
      "tiempo_estimado": "25 min",
      "material_necesario": ["Escenario con payload y viento enfrentado", "Plantilla de evaluacion", "Ficha de errores habituales"],
      "contexto": "La autonomia de bateria varia segun el peso de la carga util y la resistencia al viento enfrentada.",
      "instrucciones_paso_a_paso": ["Lee el escenario.", "Marca que parte corresponde a carga util.", "Marca que parte corresponde a resistencia al viento.", "Indica por que la autonomia nominal puede no servir.", "Justifica que comprobaciones pedirias antes de operar."],
      "criterios_de_exito": ["El alumno diferencia autonomia nominal y real.", "Incluye carga util y viento enfrentado.", "Relaciona CG desplazado con consumo prematuro cuando proceda."],
      "errores_habituales": ["Usar autonomia nominal como dato fijo.", "Ignorar resistencia al viento.", "Separar bateria de rendimiento."],
      "conceptos_relacionados": ["Autonomia", "Carga util", "Resistencia al viento", "Bateria", "Rendimiento"],
      "referencia_al_bloque": "Bloque 5 A2 - Conceptos variables"
    },
    {
      "id": "B5-PRA-009",
      "titulo": "Auditoria A/B/C de rendimiento",
      "objetivo": "Clasificar contenidos del Bloque 5 como imprescindibles, complementarios o fuera de alcance.",
      "dificultad": "alta",
      "tiempo_estimado": "30 min",
      "material_necesario": ["Lista de conceptos mezclados", "Tabla A/B/C", "Ingenieria del bloque"],
      "contexto": "La auditoria distingue contenidos imprescindibles, complementarios y fuera del alcance del A2.",
      "instrucciones_paso_a_paso": ["Coloca ejes, CG, MTOM, fuerzas y densidad en imprescindible.", "Coloca diferencia detallada de presiones e impacto especifico de humedad en complementario.", "Coloca BVLOS y centro de presiones avanzado para ala fija fuera de alcance.", "Justifica cada clasificacion con una frase.", "Revisa que no desarrollas el apartado fuera de alcance."],
      "criterios_de_exito": ["La clasificacion coincide con la auditoria.", "El alumno no desarrolla BVLOS.", "La justificacion usa solo conocimiento disponible."],
      "errores_habituales": ["Desarrollar contenido fuera de alcance.", "Convertir lo complementario en imprescindible.", "Omitir densidad del aire."],
      "conceptos_relacionados": ["Auditoria", "Imprescindible", "Complementario", "Fuera del alcance"],
      "referencia_al_bloque": "Bloque 5 A2 - Auditoria"
    },
    {
      "id": "B5-PRA-010",
      "titulo": "Diagnostico integral de rendimiento",
      "objetivo": "Integrar fuerzas, CG, MTOM, densidad, calibracion, Indice K y autonomia en una comprobacion razonada.",
      "dificultad": "alta",
      "tiempo_estimado": "35 min",
      "material_necesario": ["Caso integrador", "Checklist de rendimiento", "Tabla de datos criticos"],
      "contexto": "El rendimiento real del UAS depende de factores fisicos, configuracion, aire, instrumentos y variables de posicionamiento.",
      "instrucciones_paso_a_paso": ["Lee el caso integrador.", "Marca factores de masa: MTOM, carga util y CG.", "Marca factores del aire: densidad, altitud, temperatura y humedad.", "Marca factores del sistema: calibracion, RPS/dron e Indice K.", "Redacta una conclusion provisional indicando que informacion falta."],
      "criterios_de_exito": ["La evaluacion integra al menos masa, aire y sensores.", "Se citan datos criticos correctos cuando proceda.", "No se inventan valores de fabricante ni procedimientos externos."],
      "errores_habituales": ["Culpar solo a la bateria.", "Ignorar software o calibracion.", "Inventar limites tecnicos no presentes."],
      "conceptos_relacionados": ["MTOM", "CG", "Densidad del aire", "Calibracion", "Indice K", "Autonomia"],
      "referencia_al_bloque": "Bloque 5 A2 - Grafo de conocimiento"
    }
  ]
}

