window.DRONLAB_A2_BLOQUE4_CHULETAS = {
  "curso": "DronLab A2",
  "bloque": "Bloque 4: Meteorologia aplicada a operaciones A2",
  "titulo": "Chuletas Bloque 4 A2",
  "chuletas": [
    {"id":"B4-CH-001","titulo":"Resumen del Bloque 4","tipo":"resumen","items":["La meteorologia A2 se aplica a entornos urbanos o industriales complejos.","Los obstaculos modifican velocidad y direccion del viento.","La nubosidad ayuda a leer el estado de la atmosfera.","VLOS debe mantenerse con claridad.","Los limites del fabricante gobiernan viento, temperatura y humedad.","La decision final se expresa como Go/No-Go."]},
    {"id":"B4-CH-002","titulo":"Flujo meteorologico","tipo":"flujo","items":["Consultar condiciones actuales y prevision","Observar topografia y obstaculos","Evaluar viento local y rachas","Comprobar nubosidad, precipitaciones y VLOS","Cruzar limites del fabricante","Decidir Go/No-Go"]},
    {"id":"B4-CH-003","titulo":"MEUH meteorologico","tipo":"esquema","items":["M significa Meteorologia.","Conecta categoria abierta con practica en campo.","Sin meteorologia, Entorno, UAS y Humano quedan comprometidos.","La meteorologia es un factor externo incontrolable.","No basta con una sensacion de buen tiempo.","Debe terminar en una decision justificada."]},
    {"id":"B4-CH-004","titulo":"Viento local y entorno","tipo":"flujo","items":["Topografia y obstaculos alteran el flujo.","Edificios o estructuras cambian velocidad y direccion.","Dos edificios paralelos pueden modificar el viento local.","Rachas pueden superar el viento medio previsto.","Microclimas urbanos varian por calle, hora, sombras, sol y trafico.","Calma en suelo no garantiza calma en altura."]},
    {"id":"B4-CH-005","titulo":"Datos criticos","tipo":"tabla","items":[{"dato":"Topografia","valor":"Evaluar efecto","uso":"Velocidad y direccion del viento"},{"dato":"Comprobacion meteorologica","valor":"Actual + prevision","uso":"Momento de operacion"},{"dato":"Estado del aire","valor":"Temperatura + humedad","uso":"Rendimiento del UAS"},{"dato":"VLOS","valor":"Ver con claridad","uso":"Abortar si se compromete"},{"dato":"Manual fabricante","valor":"Limites tecnicos","uso":"Seguridad no garantizada fuera de limite"},{"dato":"Rachas","valor":"Variables","uso":"Pueden superar viento medio"},{"dato":"Humedad alta","valor":"Condensacion","uso":"Sensores de vision y posicion"},{"dato":"Meteorologia examen","valor":"75%","uso":"Pesa en el total necesario"}]},
    {"id":"B4-CH-006","titulo":"Errores habituales","tipo":"tabla","items":[{"error":"Confiar en buen tiempo en suelo","evita":"Evaluar altura, edificios y capas superiores."},{"error":"Pensar que obstaculo solo cambia velocidad","evita":"Considerar tambien direccion."},{"error":"Usar prevision antigua","evita":"Revisar condiciones actuales."},{"error":"Planificar solo con viento medio","evita":"Considerar rachas."},{"error":"Ver nubes como decoracion","evita":"Relacionar con VLOS y cambios bruscos."},{"error":"Pensar que niebla solo reduce visibilidad","evita":"Considerar sensores de vision."},{"error":"Mirar solo viento","evita":"Incluir temperatura y humedad."},{"error":"Desarrollar METAR/TAF","evita":"Marcar fuera del alcance A2."}]},
    {"id":"B4-CH-007","titulo":"Checklist final","tipo":"checklist","items":["Prevision consultada para lugar y hora.","Condiciones actuales revisadas.","Topografia y obstaculos observados.","Viento local y rachas considerados.","Nubosidad y precipitaciones valoradas.","VLOS posible con claridad.","Manual revisado: viento, temperatura y humedad.","Temperatura y humedad aplicadas al rendimiento.","Decision Go/No-Go justificada."]}
  ]
}

