window.DRONLAB_A2_BLOQUE3_CASOS = {
  "curso": "DronLab A2",
  "bloque": "Bloque 3: Operaciones en Subcategoria A2",
  "titulo": "Casos practicos Bloque 3 A2",
  "total": 12,
  "distribucion": {
    "baja": 5,
    "media": 5,
    "alta": 2
  },
  "casos": [
    {
      "id": "B3-CASO-001",
      "titulo": "Grabacion de fachada con peatones",
      "dificultad": "baja",
      "contexto": "Un piloto prepara la grabacion de un edificio de oficinas con peatones en la acera de enfrente.",
      "situacion_inicial": "El piloto dispone de certificado A2 y UAS C2, pero debe decidir como situar el dron respecto a personas no participantes.",
      "informacion_disponible": ["La ingenieria cita este escenario como uso de 30 m.", "La distancia horizontal general es 30 metros.", "Los peatones de la acera son personas no participantes si son ajenos a la operacion."],
      "problema_planteado": "Planificar la trayectoria sin tratar la acera como espacio vacio.",
      "preguntas_para_el_alumno": ["Que personas condicionan la operacion?", "Que distancia horizontal general debe considerarse?", "Que error aparece si el piloto mira solo al edificio?"],
      "objetivos_de_aprendizaje": ["Identificar personas no participantes.", "Aplicar la distancia horizontal general.", "Traducir el dato de 30 m a una trayectoria segura."],
      "errores_habituales": ["Ignorar peatones presentes.", "Confundir entorno urbano con permiso para acercarse sin condiciones."],
      "conceptos_relacionados": ["Personas no participantes", "Distancia horizontal general", "30 metros", "Planificacion de trayectorias"],
      "referencia_al_bloque": "Bloque 3 A2 - Escenario edificio de oficinas"
    },
    {
      "id": "B3-CASO-002",
      "titulo": "Inspeccion de antena en azotea",
      "dificultad": "baja",
      "contexto": "Un piloto inspecciona una antena en una azotea con operarios no relacionados a 10 metros.",
      "situacion_inicial": "El piloto quiere acercarse para inspeccionar detalles, pero debe decidir que condicion tecnica aplicar.",
      "informacion_disponible": ["La ingenieria cita este escenario como uso de modo lento y 5 m.", "La distancia reducida es 5 m como minimo absoluto.", "La reduccion depende del modo de baja velocidad."],
      "problema_planteado": "Determinar que debe verificarse antes de reducir distancia cerca de operarios no relacionados.",
      "preguntas_para_el_alumno": ["Son los operarios participantes automaticamente?", "Que modo debe estar activo?", "Que distancia actua como minimo absoluto?"],
      "objetivos_de_aprendizaje": ["Relacionar operarios no relacionados con personas no participantes.", "Aplicar modo lento antes de distancia reducida.", "Evitar usar 5 m sin condicion tecnica."],
      "errores_habituales": ["Suponer que los operarios son participantes.", "Aplicar 5 m sin modo lento verificado."],
      "conceptos_relacionados": ["Modo de baja velocidad", "5 metros", "Personas no participantes", "Inspeccion detallada"],
      "referencia_al_bloque": "Bloque 3 A2 - Escenario antena"
    },
    {
      "id": "B3-CASO-003",
      "titulo": "Cliente confundido con participante",
      "dificultad": "baja",
      "contexto": "Una persona contratante observa la operacion desde una zona cercana al vuelo.",
      "situacion_inicial": "El piloto considera que, al ser cliente, la persona forma parte de la operacion y no revisa la distancia.",
      "informacion_disponible": ["La ingenieria diferencia personas participantes y no participantes.", "No basta ser cliente o personal propio si no hay instrucciones de seguridad previas.", "La distancia se aplica a personas no participantes."],
      "problema_planteado": "Clasificar correctamente a la persona antes de decidir distancias.",
      "preguntas_para_el_alumno": ["Que informacion falta para considerarla participante?", "Que error evita comprender este concepto puente?", "Que distancia debe analizarse si no es participante?"],
      "objetivos_de_aprendizaje": ["Distinguir relacion comercial y participacion segura.", "Aplicar el concepto puente de personas.", "Evitar sobrevolar o acercarse a personas no instruidas."],
      "errores_habituales": ["Creer que el cliente es participante por defecto.", "No pedir evidencia de instrucciones de seguridad."],
      "conceptos_relacionados": ["Personas participantes", "Personas no participantes", "Instrucciones de seguridad", "Distancias A2"],
      "referencia_al_bloque": "Bloque 3 A2 - Personas participantes vs no participantes"
    },
    {
      "id": "B3-CASO-004",
      "titulo": "Modo lento asumido pero no verificado",
      "dificultad": "baja",
      "contexto": "Antes de acercarse a personas no participantes, el piloto cree que el modo de baja velocidad esta activo.",
      "situacion_inicial": "El indicador de la RPS no se revisa antes de reducir distancia.",
      "informacion_disponible": ["La ingenieria cita como error operacional confiar en que el modo lento esta activo sin verificar el indicador en la RPS.", "El modo lento permite reducir la distancia hacia 5 m.", "La velocidad en modo lento es menor o igual a 3 m/s."],
      "problema_planteado": "Identificar que comprobacion falta antes de acercarse.",
      "preguntas_para_el_alumno": ["Que debe verificar el piloto?", "Que dato de velocidad debe recordar?", "Por que no basta creer que el modo esta activo?"],
      "objetivos_de_aprendizaje": ["Vincular modo lento y RPS.", "Aplicar 3 m/s como dato critico.", "Convertir la reduccion de distancia en comprobacion operativa."],
      "errores_habituales": ["Confiar en memoria o costumbre.", "Separar 5 m de 3 m/s."],
      "conceptos_relacionados": ["Modo de baja velocidad", "RPS", "3 m/s", "5 metros"],
      "referencia_al_bloque": "Bloque 3 A2 - Riesgo operacional"
    },
    {
      "id": "B3-CASO-005",
      "titulo": "Subida del dron junto a una persona",
      "dificultad": "baja",
      "contexto": "Durante una toma, el piloto asciende el dron mientras mantiene la misma posicion horizontal respecto a una persona no participante.",
      "situacion_inicial": "El piloto recuerda la regla 1:1, pero no la recalcula al cambiar la altura.",
      "informacion_disponible": ["La regla 1:1 indica que la distancia horizontal no debe ser inferior a la altura.", "La ingenieria advierte que la regla es dinamica.", "Si subes el dron, debes alejarte mas de la persona."],
      "problema_planteado": "Detectar por que la distancia inicial puede dejar de ser suficiente.",
      "preguntas_para_el_alumno": ["Que dato cambia durante la maniobra?", "Que obliga a revisar la regla 1:1?", "Que error habitual se esta cometiendo?"],
      "objetivos_de_aprendizaje": ["Aplicar regla 1:1 dinamica.", "Relacionar altura y distancia horizontal.", "Evitar mantener distancias fijas durante ascenso."],
      "errores_habituales": ["Olvidar que la regla es dinamica.", "Memorizar 1:1 sin aplicarla al cambio de altura."],
      "conceptos_relacionados": ["Regla 1:1", "Altura AGL", "Distancia horizontal", "Monitorizacion constante"],
      "referencia_al_bloque": "Bloque 3 A2 - Regla 1:1"
    },
    {
      "id": "B3-CASO-006",
      "titulo": "Persona entra en el radio de 5 m",
      "dificultad": "media",
      "contexto": "El dron opera en modo lento cerca de una zona donde puede aparecer una persona no participante.",
      "situacion_inicial": "Una persona entra corriendo en el radio de 5 m mientras el dron permanece en modo de baja velocidad.",
      "informacion_disponible": ["La distancia de 5 m es minimo absoluto.", "El modo lento no elimina la necesidad de monitorizar distancias.", "La ingenieria plantea esta pregunta como decision nacida del bloque."],
      "problema_planteado": "Decidir que criterio de seguridad debe guiar al piloto sin inventar procedimientos no citados.",
      "preguntas_para_el_alumno": ["Que significa minimo absoluto?", "Por que el modo lento no resuelve todo?", "Que prioridad operativa aparece en esta situacion?"],
      "objetivos_de_aprendizaje": ["Interpretar una situacion dinamica.", "Justificar la recuperacion de margen de seguridad.", "No convertir modo lento en permiso para permanecer dentro de 5 m."],
      "errores_habituales": ["Creer que el modo lento basta.", "No reaccionar ante cambios de personas en tierra."],
      "conceptos_relacionados": ["5 metros", "Modo lento", "Monitorizacion constante", "Personas no participantes"],
      "referencia_al_bloque": "Bloque 3 A2 - Preguntas que nacen del bloque"
    },
    {
      "id": "B3-CASO-007",
      "titulo": "Estimacion visual con poca iluminacion",
      "dificultad": "media",
      "contexto": "El piloto opera en condiciones de iluminacion que dificultan estimar distancias con precision.",
      "situacion_inicial": "El piloto cree que una persona esta a mas de 30 m, pero la percepcion visual no es fiable.",
      "informacion_disponible": ["La estimacion visual de 30 m o 5 m varia segun iluminacion.", "Tambien influye el tamano del UAS.", "La distancia de 30 m depende de consciencia situacional y evaluacion visual."],
      "problema_planteado": "Valorar como afecta la incertidumbre visual a la decision de distancia.",
      "preguntas_para_el_alumno": ["Que variable afecta a la percepcion?", "Por que la distancia aparente puede ser peligrosa?", "Que concepto de dependencia aparece con 30 m?"],
      "objetivos_de_aprendizaje": ["Reconocer estimacion visual como variable.", "Aplicar prudencia en distancias criticas.", "Relacionar consciencia situacional y distancia horizontal."],
      "errores_habituales": ["Confiar totalmente en la sensacion visual.", "Tratar 30 m como facil de estimar en cualquier condicion."],
      "conceptos_relacionados": ["Estimacion visual", "Iluminacion", "Tamano del UAS", "Consciencia situacional"],
      "referencia_al_bloque": "Bloque 3 A2 - Conceptos variables"
    },
    {
      "id": "B3-CASO-008",
      "titulo": "Acera que se densifica",
      "dificultad": "media",
      "contexto": "Una operacion empieza con poca presencia de personas y cambia durante el vuelo.",
      "situacion_inicial": "La densidad de peatones aumenta y aparecen rafagas que pueden desplazar el UAS.",
      "informacion_disponible": ["La evaluacion del riesgo en tierra depende de la densidad de personas.", "Tambien depende de la capacidad del piloto para reaccionar ante rafagas de viento.", "La aplicacion final del grafo es monitorizacion constante de distancias."],
      "problema_planteado": "Reevaluar la operacion cuando cambian las condiciones en tierra.",
      "preguntas_para_el_alumno": ["Que variables han cambiado?", "Por que no basta la planificacion inicial?", "Que concepto final del grafo debe aplicarse?"],
      "objetivos_de_aprendizaje": ["Aplicar evaluacion variable del riesgo en tierra.", "Entender la monitorizacion constante.", "Relacionar densidad, viento y distancia."],
      "errores_habituales": ["Mantener el plan inicial sin reevaluar.", "Cumplir un numero sin mirar el entorno."],
      "conceptos_relacionados": ["Riesgo en tierra", "Densidad de personas", "Rafagas de viento", "Monitorizacion constante"],
      "referencia_al_bloque": "Bloque 3 A2 - Conceptos variables y grafo"
    },
    {
      "id": "B3-CASO-009",
      "titulo": "Confusion entre 8 km y 30 m",
      "dificultad": "media",
      "contexto": "Un alumno mezcla distancias geograficas con distancias operativas en una planificacion.",
      "situacion_inicial": "Al hablar de distancia a personas, introduce referencias a zonas de seguridad de aerodromos de 8 km.",
      "informacion_disponible": ["La auditoria clasifica diferencias con zonas de aerodromos de 8 km como complementarias.", "Sirven para evitar confundir distancias operativas con geograficas.", "Las distancias criticas del bloque son 30 m y 5 m."],
      "problema_planteado": "Separar distancias operativas frente a personas de referencias geograficas complementarias.",
      "preguntas_para_el_alumno": ["Que distancias pertenecen al nucleo A2 del bloque?", "Como clasifica la ingenieria los 8 km?", "Que confusion debe evitarse?"],
      "objetivos_de_aprendizaje": ["Distinguir metros operativos y kilometros geograficos.", "Clasificar contenido complementario.", "Evitar usar datos fuera de contexto."],
      "errores_habituales": ["Mezclar 8 km con 30 m o 5 m.", "Responder con distancias geograficas a preguntas de personas."],
      "conceptos_relacionados": ["30 metros", "5 metros", "Distancias operativas", "Contenido complementario"],
      "referencia_al_bloque": "Bloque 3 A2 - Auditoria B"
    },
    {
      "id": "B3-CASO-010",
      "titulo": "Concentracion de personas en la zona",
      "dificultad": "media",
      "contexto": "Durante una operacion prevista en categoria abierta, se detecta una concentracion de personas en la zona.",
      "situacion_inicial": "El piloto plantea si el modo lento y el UAS C2 permiten mantener el vuelo sobre esa concentracion.",
      "informacion_disponible": ["La prohibicion de concentraciones aparece como concepto estable.", "Nunca se vuela sobre multitudes en categoria abierta.", "La distancia reducida no se presenta como excepcion para concentraciones."],
      "problema_planteado": "Determinar si C2 o modo lento cambian la prohibicion estable.",
      "preguntas_para_el_alumno": ["Que concepto estable aparece?", "Que papel tienen C2 y modo lento en esta situacion?", "Que error de examen se parece a este caso?"],
      "objetivos_de_aprendizaje": ["Aplicar prohibicion de concentraciones.", "Evitar buscar excepciones no presentes.", "Diferenciar proximidad y sobrevuelo."],
      "errores_habituales": ["Creer que C2 permite sobrevolar multitudes.", "Usar modo lento como permiso general."],
      "conceptos_relacionados": ["Concentraciones", "Categoria abierta", "Sobrevuelo", "Modo lento"],
      "referencia_al_bloque": "Bloque 3 A2 - Conceptos estables"
    },
    {
      "id": "B3-CASO-011",
      "titulo": "Trayectoria con sobrevuelo deliberado",
      "dificultad": "alta",
      "contexto": "Un piloto diseña una trayectoria que pasa directamente sobre personas ajenas porque el UAS es C2.",
      "situacion_inicial": "El piloto argumenta que A2 permite volar cerca de personas y por tanto puede sobrevolarlas deliberadamente.",
      "informacion_disponible": ["La ingenieria cita como error de examen creer que C2 puede volar sobre personas ajenas deliberadamente.", "En A2 deben mantenerse 30 m o 5 m.", "El sobrevuelo se vincula a subcategoria A1 como dependencia, pero el vuelo sobre personas esta prohibido en A2 en la tabla."],
      "problema_planteado": "Corregir la interpretacion sin desarrollar subcategoria A1 fuera del alcance del bloque.",
      "preguntas_para_el_alumno": ["Que error conceptual comete el piloto?", "Que distancias vuelven a aparecer?", "Como debe tratarse la referencia a A1?"],
      "objetivos_de_aprendizaje": ["Distinguir cercania y sobrevuelo.", "Evitar usar C2 como permiso de sobrevuelo.", "Mantener el alcance del Bloque 3 A2."],
      "errores_habituales": ["Confundir cerca con encima.", "Usar reglas de otra subcategoria para justificar A2."],
      "conceptos_relacionados": ["Sobrevuelo", "C2", "30 metros", "5 metros", "Subcategoria A1 como contraste"],
      "referencia_al_bloque": "Bloque 3 A2 - Riesgos de examen y dependencias"
    },
    {
      "id": "B3-CASO-012",
      "titulo": "Operacion completa con cambios de altura y personas",
      "dificultad": "alta",
      "contexto": "Un piloto planifica una operacion A2 con personas no participantes, cambios de altura y posible reduccion de distancia.",
      "situacion_inicial": "El vuelo empieza a distancia general, luego se pretende acercar el dron en modo lento y finalmente subir altura para encuadrar mejor.",
      "informacion_disponible": ["El grafo parte de identificacion de personas no participantes y volumen operacional.", "Los conceptos centrales son modo de baja velocidad <3 m/s, regla 1:1 y limite de 5 m.", "La aplicacion final es planificacion de trayectorias seguras y monitorizacion constante de distancias."],
      "problema_planteado": "Ordenar las decisiones del piloto para no aplicar datos aislados fuera de contexto.",
      "preguntas_para_el_alumno": ["Que debe identificarse primero?", "Que condicion permite reducir distancia?", "Que debe reevaluarse al subir altura?", "Que significa monitorizacion constante en este caso?"],
      "objetivos_de_aprendizaje": ["Aplicar el grafo completo.", "Conectar personas, entorno, modo lento y regla 1:1.", "Justificar decisiones operativas con datos criticos."],
      "errores_habituales": ["Saltar directamente a 5 m.", "Olvidar la regla 1:1 al subir.", "No monitorizar cambios en personas o entorno."],
      "conceptos_relacionados": ["Grafo de conocimiento", "Modo lento", "Regla 1:1", "5 metros", "30 metros", "Monitorizacion constante"],
      "referencia_al_bloque": "Bloque 3 A2 - Sintesis operativa"
    }
  ]
}
;
