window.DRONLAB_A2_BLOQUE2_FLASHCARDS = {
  "curso": "DronLab A2",
  "bloque": "Bloque 2: El Sistema UAS de Clase C2",
  "titulo": "Flashcards Bloque 2 A2",
  "total": 45,
  "distribucion": {
    "facil": 18,
    "media": 18,
    "dificil": 9
  },
  "fuera_alcance": ["STS", "SORA", "Categoria Especifica", "Categoria Certificada", "Radiofonista UAS", "STS-ES"],
  "flashcards": [
    {
      "id": "B2-FC-001",
      "tema": "UAS de Clase C2",
      "subtema": "Definicion",
      "dificultad": "facil",
      "tipo": "concepto",
      "pregunta": "Que es un UAS de clase C2?",
      "respuesta": "Una aeronave no tripulada con MTOM inferior a 4 kg, marcado de clase oficial y requisitos tecnicos del Reglamento (UE) 2019/945.",
      "explicacion_breve": "La definicion combina masa, marcado oficial y requisitos tecnicos.",
      "error_habitual": "Pensar que C2 es cualquier dron que pesa poco.",
      "regla_mnemotecnica": "C2 = clase, kg y requisitos."
    },
    {
      "id": "B2-FC-002",
      "tema": "UAS de Clase C2",
      "subtema": "MTOM",
      "dificultad": "facil",
      "tipo": "dato critico",
      "pregunta": "Cual es la MTOM de la clase C2?",
      "respuesta": "Inferior a 4 kg.",
      "explicacion_breve": "La ingenieria lo clasifica como dato estable y critico.",
      "error_habitual": "Responder 4 kg exactos o mezclarlo con otros limites.",
      "regla_mnemotecnica": "C2 pesa menos de 4."
    },
    {
      "id": "B2-FC-003",
      "tema": "UAS de Clase C2",
      "subtema": "Marcado",
      "dificultad": "facil",
      "tipo": "concepto",
      "pregunta": "Que marcado debe tener fisicamente un UAS C2?",
      "respuesta": "Una etiqueta fisica de clase C2.",
      "explicacion_breve": "El marcado de clase oficial es una dependencia de la clase C2.",
      "error_habitual": "Fiarse solo del nombre comercial del producto.",
      "regla_mnemotecnica": "Si no hay etiqueta, no basta la etiqueta comercial."
    },
    {
      "id": "B2-FC-004",
      "tema": "UAS de Clase C2",
      "subtema": "Finalidad",
      "dificultad": "facil",
      "tipo": "concepto",
      "pregunta": "Para que sirve la clase C2 en A2?",
      "respuesta": "Para permitir la operatividad en subcategoria A2 cerca de personas con estandares de seguridad y mitigacion de danos.",
      "explicacion_breve": "La clase C2 conecta requisitos tecnicos con reduccion de riesgo.",
      "error_habitual": "Ver C2 como una etiqueta sin funcion de seguridad.",
      "regla_mnemotecnica": "C2 acerca, pero mitiga."
    },
    {
      "id": "B2-FC-005",
      "tema": "UAS de Clase C2",
      "subtema": "Importancia",
      "dificultad": "dificil",
      "tipo": "relacion",
      "pregunta": "Por que la clase C2 es critica para reducir distancias de seguridad?",
      "respuesta": "Porque es el unico tipo de dron con marcado de clase citado como habilitado para reducir distancias hasta los 5 metros.",
      "explicacion_breve": "La distancia reducida depende del sistema y sus mitigaciones.",
      "error_habitual": "Aplicar la distancia de 5 m a cualquier UAS.",
      "regla_mnemotecnica": "5 m solo con C2 y mitigacion."
    },
    {
      "id": "B2-FC-006",
      "tema": "UAS de Clase C2",
      "subtema": "Dependencias basicas",
      "dificultad": "facil",
      "tipo": "lista",
      "pregunta": "Que tres dependencias basicas cita la fuente para el UAS C2?",
      "respuesta": "Etiqueta fisica de clase C2, numero de serie unico y fuente de alimentacion electrica.",
      "explicacion_breve": "Son elementos que permiten reconocer y verificar el sistema.",
      "error_habitual": "Olvidar el numero de serie o la alimentacion electrica.",
      "regla_mnemotecnica": "Etiqueta, serie, energia."
    },
    {
      "id": "B2-FC-007",
      "tema": "Modo de baja velocidad",
      "subtema": "Definicion",
      "dificultad": "facil",
      "tipo": "concepto",
      "pregunta": "Que es el modo de baja velocidad?",
      "respuesta": "Una funcion seleccionable desde la estacion de control que limita la velocidad de avance del UAS.",
      "explicacion_breve": "Es una funcion que el piloto gestiona desde el control.",
      "error_habitual": "Pensar que es una condicion ambiental y no una funcion seleccionable.",
      "regla_mnemotecnica": "Modo lento se selecciona."
    },
    {
      "id": "B2-FC-008",
      "tema": "Modo de baja velocidad",
      "subtema": "Valor limite",
      "dificultad": "facil",
      "tipo": "dato critico",
      "pregunta": "A que velocidad maxima limita el modo de baja velocidad?",
      "respuesta": "A un maximo de 3 m/s.",
      "explicacion_breve": "La fuente lo marca como limite estable.",
      "error_habitual": "No asociar el modo lento con el valor 3 m/s.",
      "regla_mnemotecnica": "Lento: 3 metros por segundo."
    },
    {
      "id": "B2-FC-009",
      "tema": "Modo de baja velocidad",
      "subtema": "Finalidad",
      "dificultad": "facil",
      "tipo": "concepto",
      "pregunta": "Que reduce el modo de baja velocidad?",
      "respuesta": "Reduce la energia de impacto y aumenta el tiempo de reaccion del piloto.",
      "explicacion_breve": "Es una mitigacion ligada a seguridad cerca de personas.",
      "error_habitual": "Creer que solo sirve para pilotar con mas comodidad.",
      "regla_mnemotecnica": "Menos velocidad, mas reaccion."
    },
    {
      "id": "B2-FC-010",
      "tema": "Modo de baja velocidad",
      "subtema": "Activacion",
      "dificultad": "dificil",
      "tipo": "aplicacion",
      "pregunta": "Quien activa el modo de baja velocidad segun la fuente?",
      "respuesta": "El piloto a distancia lo activa manualmente, excepto en ala fija donde no aplica esta reduccion.",
      "explicacion_breve": "La activacion manual es una dependencia operativa.",
      "error_habitual": "Suponer que se activa automaticamente siempre que hay personas.",
      "regla_mnemotecnica": "El piloto decide el modo."
    },
    {
      "id": "B2-FC-011",
      "tema": "Vuelo cerca de personas",
      "subtema": "5 metros",
      "dificultad": "media",
      "tipo": "dependencia",
      "pregunta": "De que depende el vuelo a 5 metros?",
      "respuesta": "Depende del modo de baja velocidad, limitado a 3 m/s.",
      "explicacion_breve": "La distancia reducida se desbloquea por una mitigacion tecnica.",
      "error_habitual": "Memorizar 5 m sin recordar la condicion.",
      "regla_mnemotecnica": "5 m cuelga de 3 m/s."
    },
    {
      "id": "B2-FC-012",
      "tema": "Vuelo cerca de personas",
      "subtema": "Legalidad",
      "dificultad": "media",
      "tipo": "aplicacion",
      "pregunta": "Por que es vital el modo de baja velocidad a menos de 30 metros de personas ajenas?",
      "respuesta": "Porque la fuente lo vincula con la legalidad del vuelo a menos de 30 metros de personas ajenas.",
      "explicacion_breve": "No es un detalle opcional cuando se reduce distancia.",
      "error_habitual": "Acercarse a personas sin activar la mitigacion.",
      "regla_mnemotecnica": "Menos de 30 m exige pensar en modo lento."
    },
    {
      "id": "B2-FC-013",
      "tema": "Identificacion a distancia directa",
      "subtema": "Definicion",
      "dificultad": "facil",
      "tipo": "concepto",
      "pregunta": "Que es la identificacion a distancia directa o DRI?",
      "respuesta": "Un sistema que emite periodicamente datos de identificacion y movimiento del UAS durante el vuelo.",
      "explicacion_breve": "Hace visible digitalmente la operacion para supervision.",
      "error_habitual": "Tratar DRI como una funcion secundaria sin impacto legal.",
      "regla_mnemotecnica": "DRI emite datos."
    },
    {
      "id": "B2-FC-014",
      "tema": "Identificacion a distancia directa",
      "subtema": "Datos emitidos",
      "dificultad": "media",
      "tipo": "lista",
      "pregunta": "Que datos emite el sistema DRI?",
      "respuesta": "Numero de operador, numero de serie, posicion, altura, trayectoria y velocidad.",
      "explicacion_breve": "La fuente enumera esos datos como contenido emitido periodicamente.",
      "error_habitual": "Olvidar trayectoria o velocidad.",
      "regla_mnemotecnica": "Operador, serie, posicion, altura, ruta y velocidad."
    },
    {
      "id": "B2-FC-015",
      "tema": "Identificacion a distancia directa",
      "subtema": "Finalidad",
      "dificultad": "facil",
      "tipo": "concepto",
      "pregunta": "Para que sirve la DRI?",
      "respuesta": "Para facilitar la vigilancia y supervision de las autoridades competentes durante el vuelo.",
      "explicacion_breve": "Su finalidad es la trazabilidad operativa.",
      "error_habitual": "Pensar que DRI solo registra datos para el piloto.",
      "regla_mnemotecnica": "DRI ayuda a supervisar."
    },
    {
      "id": "B2-FC-016",
      "tema": "Identificacion a distancia directa",
      "subtema": "Numero de operador",
      "dificultad": "media",
      "tipo": "dependencia",
      "pregunta": "Que numero debe cargarse previamente para la DRI?",
      "respuesta": "El numero de registro de operador obtenido en la sede electronica de AESA.",
      "explicacion_breve": "La DRI depende de esa carga previa.",
      "error_habitual": "Cargar el numero de identificacion de piloto ESP-RP en lugar del numero de operador.",
      "regla_mnemotecnica": "DRI identifica operador."
    },
    {
      "id": "B2-FC-017",
      "tema": "Identificacion a distancia directa",
      "subtema": "Operacion invalida",
      "dificultad": "dificil",
      "tipo": "riesgo",
      "pregunta": "Que efecto tiene la falta de carga del numero de operador o el mal funcionamiento de DRI?",
      "respuesta": "Invalida la operacion segun la ingenieria del bloque.",
      "explicacion_breve": "La DRI tiene importancia alta para la legalidad de la aeronave en vuelo.",
      "error_habitual": "Despegar sin comprobar que DRI funciona y contiene el dato correcto.",
      "regla_mnemotecnica": "Sin operador en DRI, no hay operacion valida."
    },
    {
      "id": "B2-FC-018",
      "tema": "Geoconsciencia",
      "subtema": "Definicion",
      "dificultad": "facil",
      "tipo": "concepto",
      "pregunta": "Que es la geoconsciencia?",
      "respuesta": "Una funcion que avisa al piloto cuando el UAS se aproxima a limites de una zona geografica restringida o prohibida.",
      "explicacion_breve": "Es una salvaguarda tecnologica ante errores de navegacion.",
      "error_habitual": "Pensar que la geoconsciencia autoriza el vuelo.",
      "regla_mnemotecnica": "Geoconsciencia avisa, no autoriza."
    },
    {
      "id": "B2-FC-019",
      "tema": "Geoconsciencia",
      "subtema": "Finalidad",
      "dificultad": "facil",
      "tipo": "concepto",
      "pregunta": "Que previene la geoconsciencia?",
      "respuesta": "Previene incursiones accidentales en espacios aereos protegidos o peligrosos.",
      "explicacion_breve": "Su funcion es advertir antes de entrar en zonas sensibles.",
      "error_habitual": "Usarla como sustituto de la planificacion.",
      "regla_mnemotecnica": "Aviso antes de incursion."
    },
    {
      "id": "B2-FC-020",
      "tema": "Geoconsciencia",
      "subtema": "Dependencia",
      "dificultad": "media",
      "tipo": "dependencia",
      "pregunta": "De que depende la geoconsciencia?",
      "respuesta": "De la actualizacion de los datos geograficos proporcionados por las autoridades, por ejemplo ENAIRE Drones.",
      "explicacion_breve": "La informacion geografica es variable y debe mantenerse actualizada.",
      "error_habitual": "Operar con bases de datos antiguas.",
      "regla_mnemotecnica": "Mapa viejo, aviso debil."
    },
    {
      "id": "B2-FC-021",
      "tema": "Enlace de mando y control",
      "subtema": "Concepto puente",
      "dificultad": "facil",
      "tipo": "concepto",
      "pregunta": "Que conecta el enlace de mando y control C2?",
      "respuesta": "Conecta la estacion de pilotaje RPS con la aeronave.",
      "explicacion_breve": "Es el puente tecnico entre mando y UAS.",
      "error_habitual": "Olvidar comprobar el enlace antes del despegue.",
      "regla_mnemotecnica": "RPS habla con aeronave."
    },
    {
      "id": "B2-FC-022",
      "tema": "Enlace de mando y control",
      "subtema": "Seguridad",
      "dificultad": "media",
      "tipo": "requisito",
      "pregunta": "Que exige la clase C2 al enlace de mando y control?",
      "respuesta": "Que este protegido contra accesos no autorizados y disponga de metodos de recuperacion ante su perdida.",
      "explicacion_breve": "No basta comunicar: el enlace debe ser seguro y recuperable.",
      "error_habitual": "Dar por hecho que cualquier enlace es valido.",
      "regla_mnemotecnica": "Enlace C2: protegido y recuperable."
    },
    {
      "id": "B2-FC-023",
      "tema": "Enlace de mando y control",
      "subtema": "Pre-vuelo",
      "dificultad": "media",
      "tipo": "aplicacion",
      "pregunta": "Que error operacional cita la fuente sobre el enlace C2?",
      "respuesta": "No verificar el funcionamiento del enlace C2 antes del despegue.",
      "explicacion_breve": "La comprobacion del enlace forma parte de la preparacion segura.",
      "error_habitual": "Despegar suponiendo que el enlace esta correcto.",
      "regla_mnemotecnica": "Antes de despegar, enlace a comprobar."
    },
    {
      "id": "B2-FC-024",
      "tema": "Avisos de bateria",
      "subtema": "Dependencia",
      "dificultad": "media",
      "tipo": "dependencia",
      "pregunta": "De que dependen los avisos de bateria?",
      "respuesta": "De sensores del UAS y de la RPS.",
      "explicacion_breve": "La fuente vincula ambos sistemas a la gestion de autonomia.",
      "error_habitual": "Mirar solo la bateria de la aeronave y olvidar la RPS.",
      "regla_mnemotecnica": "Bateria se mira en UAS y RPS."
    },
    {
      "id": "B2-FC-025",
      "tema": "Avisos de bateria",
      "subtema": "Finalidad",
      "dificultad": "facil",
      "tipo": "concepto",
      "pregunta": "Que desbloquean los avisos de bateria?",
      "respuesta": "La gestion de autonomia y un RTH o aterrizaje seguro.",
      "explicacion_breve": "El aviso debe llegar con margen para decidir.",
      "error_habitual": "Esperar a que la bateria sea critica para reaccionar.",
      "regla_mnemotecnica": "Aviso temprano, aterrizaje seguro."
    },
    {
      "id": "B2-FC-026",
      "tema": "Avisos de bateria",
      "subtema": "Margen",
      "dificultad": "media",
      "tipo": "variable",
      "pregunta": "Por que el margen de aviso de bateria es variable?",
      "respuesta": "Porque es ajustable segun la resistencia y distancia de la operacion.",
      "explicacion_breve": "No todas las operaciones necesitan el mismo margen.",
      "error_habitual": "Usar siempre el mismo margen sin considerar distancia.",
      "regla_mnemotecnica": "Mas distancia, mas margen."
    },
    {
      "id": "B2-FC-027",
      "tema": "Altura",
      "subtema": "Dato critico",
      "dificultad": "facil",
      "tipo": "dato critico",
      "pregunta": "Que altura maxima aparece en la ingenieria del Bloque 2?",
      "respuesta": "120 metros.",
      "explicacion_breve": "Aparece como techo limitado por software o configuracion.",
      "error_habitual": "Mezclar este dato con autorizaciones no tratadas en el bloque.",
      "regla_mnemotecnica": "C2 recuerda 120 m."
    },
    {
      "id": "B2-FC-028",
      "tema": "Luces",
      "subtema": "Requisito estable",
      "dificultad": "facil",
      "tipo": "requisito",
      "pregunta": "Que requisito de luces recoge la fuente?",
      "respuesta": "Luces visibles de noche y para control de altitud.",
      "explicacion_breve": "Es uno de los conceptos estables del bloque.",
      "error_habitual": "Centrarse solo en software y olvidar requisitos visibles.",
      "regla_mnemotecnica": "Luces para noche y altura."
    },
    {
      "id": "B2-FC-029",
      "tema": "Software y firmware",
      "subtema": "Actualizacion",
      "dificultad": "facil",
      "tipo": "variable",
      "pregunta": "Que version de software o firmware debe usarse?",
      "respuesta": "La ultima publicada por el fabricante, tanto en aeronave como en RPS.",
      "explicacion_breve": "La version es variable y depende del fabricante.",
      "error_habitual": "Actualizar solo una parte del sistema.",
      "regla_mnemotecnica": "Ultima version en dron y RPS."
    },
    {
      "id": "B2-FC-030",
      "tema": "Software y firmware",
      "subtema": "Escenario",
      "dificultad": "media",
      "tipo": "aplicacion",
      "pregunta": "Que puede ocurrir si el software de la RPS no coincide con el del dron?",
      "respuesta": "Puede impedir el despegue por seguridad, segun el escenario implicito.",
      "explicacion_breve": "El sistema UAS incluye aeronave y estacion de pilotaje.",
      "error_habitual": "No revisar compatibilidad antes del vuelo.",
      "regla_mnemotecnica": "RPS y dron deben ir acompasados."
    },
    {
      "id": "B2-FC-031",
      "tema": "Componentes amovibles",
      "subtema": "Riesgo habitual",
      "dificultad": "facil",
      "tipo": "riesgo",
      "pregunta": "Que error habitual cita la fuente sobre componentes amovibles?",
      "respuesta": "No asegurar correctamente componentes como helices o camaras.",
      "explicacion_breve": "La seguridad tambien depende de la inspeccion fisica.",
      "error_habitual": "Olvidar componentes desmontables en la revision previa.",
      "regla_mnemotecnica": "Helices y camaras, bien fijadas."
    },
    {
      "id": "B2-FC-032",
      "tema": "Errores de examen",
      "subtema": "Confusion de clases",
      "dificultad": "media",
      "tipo": "examen",
      "pregunta": "Con que limites se confunde a menudo la MTOM de C2?",
      "respuesta": "Con C1 de 900 g o C3 de 25 kg.",
      "explicacion_breve": "La fuente cita esta confusion como error de examen.",
      "error_habitual": "Responder 900 g o 25 kg cuando preguntan por C2.",
      "regla_mnemotecnica": "C2 no es 900 g ni 25 kg."
    },
    {
      "id": "B2-FC-033",
      "tema": "Datos criticos",
      "subtema": "Indice K",
      "dificultad": "media",
      "tipo": "dato critico",
      "pregunta": "Que valor de indice K aparece en los datos criticos?",
      "respuesta": "Indice K inferior a 4 para operar.",
      "explicacion_breve": "La ingenieria lo lista como valor critico, sin desarrollar mas detalle.",
      "error_habitual": "Intentar desarrollar informacion no presente sobre el indice K.",
      "regla_mnemotecnica": "K debe ser menor que 4."
    },
    {
      "id": "B2-FC-034",
      "tema": "Datos criticos",
      "subtema": "DRI",
      "dificultad": "media",
      "tipo": "memorizacion",
      "pregunta": "Que seis datos debes recordar sobre la emision DRI?",
      "respuesta": "Numero de operador, serie, posicion, altura, trayectoria y velocidad.",
      "explicacion_breve": "Son los datos exactos que aparecen en la fuente.",
      "error_habitual": "Anadir datos no citados o dejar fuera uno de los seis.",
      "regla_mnemotecnica": "OS-PATV: operador, serie, posicion, altura, trayectoria, velocidad."
    },
    {
      "id": "B2-FC-035",
      "tema": "Instrucciones del fabricante",
      "subtema": "Concepto puente",
      "dificultad": "media",
      "tipo": "relacion",
      "pregunta": "Que conectan las instrucciones del fabricante?",
      "respuesta": "Conectan el conocimiento general del UAS con la operativa especifica A2.",
      "explicacion_breve": "Permiten verificar limites de peso, bateria y modo de baja velocidad.",
      "error_habitual": "Operar sin revisar limites indicados por el fabricante.",
      "regla_mnemotecnica": "Manual primero, operativa despues."
    },
    {
      "id": "B2-FC-036",
      "tema": "Instrucciones del fabricante",
      "subtema": "Verificaciones",
      "dificultad": "media",
      "tipo": "aplicacion",
      "pregunta": "Que limites ayudan a verificar las instrucciones del fabricante?",
      "respuesta": "Limites de peso, bateria y configuracion del modo de baja velocidad.",
      "explicacion_breve": "La fuente cita esas verificaciones dentro del concepto puente.",
      "error_habitual": "Separar el manual de la configuracion real del equipo.",
      "regla_mnemotecnica": "Peso, bateria, modo lento."
    },
    {
      "id": "B2-FC-037",
      "tema": "Grafo de conocimiento",
      "subtema": "Conceptos iniciales",
      "dificultad": "dificil",
      "tipo": "estructura",
      "pregunta": "Que conceptos iniciales abre el grafo del Bloque 2?",
      "respuesta": "Marcado de Clase C2, MTOM inferior a 4 kg y alimentacion electrica.",
      "explicacion_breve": "Son la base antes de configurar funciones y aplicar operaciones.",
      "error_habitual": "Empezar por el vuelo a 5 m sin verificar el sistema.",
      "regla_mnemotecnica": "Primero clase, masa y energia."
    },
    {
      "id": "B2-FC-038",
      "tema": "Grafo de conocimiento",
      "subtema": "Conceptos centrales",
      "dificultad": "dificil",
      "tipo": "estructura",
      "pregunta": "Que conceptos centrales aparecen antes de la aplicacion?",
      "respuesta": "Gestion del modo de baja velocidad y avisos de bateria baja en UAS y RPS.",
      "explicacion_breve": "Son funciones clave para decidir durante la operacion.",
      "error_habitual": "Tratar bateria o modo lento como detalles secundarios.",
      "regla_mnemotecnica": "Centro: lento y bateria."
    },
    {
      "id": "B2-FC-039",
      "tema": "Grafo de conocimiento",
      "subtema": "Aplicacion",
      "dificultad": "dificil",
      "tipo": "estructura",
      "pregunta": "Que aplicacion final propone el grafo del Bloque 2?",
      "respuesta": "Vuelo a 5 m de personas ajenas y gestion de fallos de sistema.",
      "explicacion_breve": "La aplicacion se alcanza tras configurar y comprender el sistema C2.",
      "error_habitual": "Intentar aplicar sin dominar dependencias.",
      "regla_mnemotecnica": "Aplicar = 5 m y fallos."
    },
    {
      "id": "B2-FC-040",
      "tema": "Escenarios reales",
      "subtema": "Inspeccion de fachada",
      "dificultad": "media",
      "tipo": "escenario",
      "pregunta": "Que debe hacer el piloto en una inspeccion de fachada con un peaton en la acera?",
      "respuesta": "Activar el modo de baja velocidad para mantener la separacion de 5 metros indicada en el escenario.",
      "explicacion_breve": "El escenario vincula distancia reducida y modo lento.",
      "error_habitual": "Centrarse en la inspeccion y olvidar la mitigacion.",
      "regla_mnemotecnica": "Fachada con peaton: modo lento."
    },
    {
      "id": "B2-FC-041",
      "tema": "Escenarios reales",
      "subtema": "Software RPS/UAS",
      "dificultad": "media",
      "tipo": "escenario",
      "pregunta": "Que debe revisar el piloto si el software de la RPS no coincide con el del dron?",
      "respuesta": "Debe revisar la actualizacion del software o firmware en aeronave y RPS.",
      "explicacion_breve": "La fuente plantea que la discrepancia puede impedir el despegue por seguridad.",
      "error_habitual": "Intentar despegar sin resolver la discrepancia.",
      "regla_mnemotecnica": "Dos equipos, una version coherente."
    },
    {
      "id": "B2-FC-042",
      "tema": "Escenarios reales",
      "subtema": "Bateria baja",
      "dificultad": "media",
      "tipo": "escenario",
      "pregunta": "Que significa un aviso de bateria baja emitido con margen suficiente?",
      "respuesta": "Que el piloto aun tiene margen para un aterrizaje seguro.",
      "explicacion_breve": "La finalidad del aviso es permitir decidir antes de que sea tarde.",
      "error_habitual": "Ignorar el aviso hasta perder margen.",
      "regla_mnemotecnica": "Aviso con margen, aterrizaje seguro."
    },
    {
      "id": "B2-FC-043",
      "tema": "Fuera de alcance",
      "subtema": "STS-ES",
      "dificultad": "dificil",
      "tipo": "alcance",
      "pregunta": "Que debe hacerse si aparece STS-ES en el Bloque 2 A2?",
      "respuesta": "Marcarlo como fuera del alcance del curso A2 y no desarrollarlo.",
      "explicacion_breve": "La auditoria de la ingenieria clasifica STS-ES fuera del alcance A2.",
      "error_habitual": "Desarrollar requisitos especificos de aeronave STS-ES.",
      "regla_mnemotecnica": "STS-ES se etiqueta, no se desarrolla."
    },
    {
      "id": "B2-FC-044",
      "tema": "Dependencias",
      "subtema": "Operaciones urbanas",
      "dificultad": "dificil",
      "tipo": "dependencia",
      "pregunta": "Que desbloquea el modo de baja velocidad en la tabla de dependencias?",
      "respuesta": "El vuelo a 5 metros y operaciones en entornos urbanos, segun la tabla de la ingenieria.",
      "explicacion_breve": "La dependencia critica es modo lento antes de distancia reducida.",
      "error_habitual": "Saltar de C2 a entorno urbano sin citar el modo lento.",
      "regla_mnemotecnica": "Modo lento desbloquea 5 m."
    },
    {
      "id": "B2-FC-045",
      "tema": "Auditoria del bloque",
      "subtema": "Imprescindible",
      "dificultad": "dificil",
      "tipo": "sintesis",
      "pregunta": "Que contenidos son imprescindibles para el Bloque 2 A2?",
      "respuesta": "Definicion C2, modo de baja velocidad, geoconsciencia, Remote ID y sistema de aviso de bateria.",
      "explicacion_breve": "Son los elementos clasificados como imprescindibles en la auditoria de la ingenieria.",
      "error_habitual": "Dedicar el bloque a contenidos complementarios o fuera de alcance.",
      "regla_mnemotecnica": "C2, lento, geo, ID y bateria."
    }
  ]
}
;
