window.DRONLAB_A2_BLOQUE4_PRACTICAS = {
  "curso": "DronLab A2",
  "bloque": "Bloque 4: Meteorologia aplicada a operaciones A2",
  "titulo": "Practicas guiadas Bloque 4 A2",
  "total": 10,
  "distribucion": {"baja": 4, "media": 4, "alta": 2},
  "practicas": [
    {
      "id": "B4-PRA-001",
      "titulo": "Checklist meteorologico inicial",
      "objetivo": "Construir una comprobacion meteorologica basica antes del despliegue.",
      "dificultad": "baja",
      "tiempo_estimado": "20 min",
      "material_necesario": ["Plantilla de checklist", "Escenario de mision", "Datos actuales y prevision simulada"],
      "contexto": "La evaluacion meteorologica exige consultar condiciones actuales y prediccion para lugar y hora de la mision.",
      "instrucciones_paso_a_paso": ["Lee el escenario propuesto.", "Anota lugar y hora de la mision.", "Separa condiciones actuales y prevision.", "Indica que informacion falta para decidir.", "Redacta una primera decision Go/No-Go justificada."],
      "criterios_de_exito": ["El alumno no mezcla prevision y condiciones actuales.", "Incluye lugar y hora.", "Justifica la decision sin inventar fuentes externas."],
      "errores_habituales": ["Usar una prevision antigua.", "Decidir por sensacion de buen tiempo.", "No indicar informacion faltante."],
      "conceptos_relacionados": ["Evaluacion meteorologica", "Condiciones actuales", "Prevision", "Go/No-Go"],
      "referencia_al_bloque": "Bloque 4 A2 - Evaluacion y prevision meteorologica"
    },
    {
      "id": "B4-PRA-002",
      "titulo": "Lectura del entorno: topografia y obstaculos",
      "objetivo": "Identificar elementos del entorno que alteran velocidad y direccion del viento.",
      "dificultad": "baja",
      "tiempo_estimado": "25 min",
      "material_necesario": ["Plano urbano simple", "Marcadores de edificios", "Flechas de viento"],
      "contexto": "El analisis de topografia es obligatorio para evaluar su efecto en velocidad y direccion del viento.",
      "instrucciones_paso_a_paso": ["Observa el plano.", "Marca edificios, estructuras y calles estrechas.", "Dibuja el viento previsto.", "Propone como podria modificarse el flujo cerca de obstaculos.", "Escribe dos riesgos para el UAS."],
      "criterios_de_exito": ["El alumno identifica obstaculos relevantes.", "Considera direccion y velocidad.", "Relaciona el entorno con comportamiento del UAS."],
      "errores_habituales": ["Pensar solo en velocidad.", "No observar edificios.", "Usar la prevision general sin entorno local."],
      "conceptos_relacionados": ["Topografia", "Obstaculos", "Efectos locales del viento", "Turbulencia urbana"],
      "referencia_al_bloque": "Bloque 4 A2 - Efectos locales del viento"
    },
    {
      "id": "B4-PRA-003",
      "titulo": "VLOS ante nubosidad y precipitaciones",
      "objetivo": "Decidir si la meteorologia permite mantener VLOS con claridad.",
      "dificultad": "baja",
      "tiempo_estimado": "20 min",
      "material_necesario": ["Ficha de cielo y visibilidad", "Tarjetas Go/No-Go", "Tabla de criterios VLOS"],
      "contexto": "El piloto debe abortar si la meteorologia impide ver el dron con claridad.",
      "instrucciones_paso_a_paso": ["Lee la descripcion de nubosidad y precipitaciones.", "Indica si la visibilidad esta comprometida.", "Relaciona la condicion con VLOS.", "Decide Go/No-Go.", "Justifica en una frase que haria cambiar la decision."],
      "criterios_de_exito": ["El alumno conecta nubosidad y VLOS.", "No continua si no hay claridad.", "Distingue plan inicial y condicion real."],
      "errores_habituales": ["Tratar nubes como decoracion.", "Continuar por inercia.", "No usar la palabra claridad."],
      "conceptos_relacionados": ["Formacion de nubes", "VLOS", "Nubosidad", "Precipitaciones"],
      "referencia_al_bloque": "Bloque 4 A2 - Formacion de nubes y prioridad VLOS"
    },
    {
      "id": "B4-PRA-004",
      "titulo": "Consulta del manual del fabricante",
      "objetivo": "Convertir los limites meteorologicos del fabricante en una comprobacion operativa.",
      "dificultad": "baja",
      "tiempo_estimado": "25 min",
      "material_necesario": ["Ficha simulada de manual", "Plantilla viento-temperatura-humedad", "Escenario de mision"],
      "contexto": "Los limites del fabricante incluyen viento maximo, rango de temperatura y humedad.",
      "instrucciones_paso_a_paso": ["Localiza en la ficha los campos de viento, temperatura y humedad.", "Copia los umbrales disponibles sin inventar valores ausentes.", "Compara esos campos con el escenario.", "Marca si la seguridad queda garantizada o no segun el manual.", "Redacta la decision tecnica."],
      "criterios_de_exito": ["El alumno consulta el manual.", "No inventa limites.", "Relaciona limite superado con seguridad no garantizada."],
      "errores_habituales": ["Usar limites genericos.", "Mirar solo viento.", "Sustituir manual por experiencia."],
      "conceptos_relacionados": ["Limites del fabricante", "Manual UAS C2", "Viento maximo", "Temperatura", "Humedad"],
      "referencia_al_bloque": "Bloque 4 A2 - Limites meteorologicos del fabricante"
    },
    {
      "id": "B4-PRA-005",
      "titulo": "Aplicacion de MEUH a una mision A2",
      "objetivo": "Usar la M de meteorologia para comprobar Entorno, UAS y Humano.",
      "dificultad": "media",
      "tiempo_estimado": "30 min",
      "material_necesario": ["Plantilla MEUH", "Escenario urbano", "Tarjetas Entorno/UAS/Humano"],
      "contexto": "Sin verificar meteorologia, los pilares de Entorno, UAS y Humano quedan comprometidos.",
      "instrucciones_paso_a_paso": ["Completa primero la M con datos meteorologicos.", "Relaciona cada dato con Entorno.", "Relaciona cada dato con UAS.", "Relaciona cada dato con Humano.", "Escribe una decision Go/No-Go basada en MEUH."],
      "criterios_de_exito": ["El alumno no trata MEUH como acronimo vacio.", "Conecta meteorologia con los otros pilares.", "Justifica la decision final."],
      "errores_habituales": ["Omitir la M.", "Separar meteorologia del UAS.", "Hacer checklist mecanico sin consecuencias."],
      "conceptos_relacionados": ["MEUH", "Meteorologia", "Entorno", "UAS", "Humano"],
      "referencia_al_bloque": "Bloque 4 A2 - Metodologia MEUH"
    },
    {
      "id": "B4-PRA-006",
      "titulo": "Rachas frente a viento medio",
      "objetivo": "Interpretar rachas como variable critica frente a un viento medio aparentemente aceptable.",
      "dificultad": "media",
      "tiempo_estimado": "25 min",
      "material_necesario": ["Grafica simple de viento medio y rachas", "Limites del fabricante simulados", "Plantilla de decision"],
      "contexto": "Las rachas no son constantes y pueden superar el viento medio previsto.",
      "instrucciones_paso_a_paso": ["Identifica el viento medio en la grafica.", "Marca los picos de racha.", "Compara ambos con el limite del manual simulado.", "Indica si el promedio oculta un riesgo.", "Justifica la decision operativa."],
      "criterios_de_exito": ["El alumno distingue media y racha.", "No decide solo por promedio.", "Cruza rachas con limites del fabricante."],
      "errores_habituales": ["Planificar solo con viento medio.", "Ignorar picos intermitentes.", "Mantener el plan aunque cambie el viento real."],
      "conceptos_relacionados": ["Rachas", "Viento medio", "Condiciones actuales", "Limites del fabricante"],
      "referencia_al_bloque": "Bloque 4 A2 - Rachas de viento"
    },
    {
      "id": "B4-PRA-007",
      "titulo": "Humedad, niebla y sensores",
      "objetivo": "Analizar la humedad alta como riesgo para VLOS y sensores de vision.",
      "dificultad": "media",
      "tiempo_estimado": "30 min",
      "material_necesario": ["Ficha de escenario con niebla", "Tabla humedad/sensor/VLOS", "Checklist del manual"],
      "contexto": "La humedad relativa muy alta puede condensar en sensores de vision del UAS C2 y provocar errores de posicion.",
      "instrucciones_paso_a_paso": ["Lee la situacion de niebla o humedad alta.", "Evalua si VLOS puede mantenerse con claridad.", "Identifica el riesgo para sensores de vision.", "Comprueba el campo de humedad del manual simulado.", "Redacta una decision justificada."],
      "criterios_de_exito": ["El alumno no limita la niebla a visibilidad.", "Incluye sensores de vision.", "Relaciona humedad con manual y posicion."],
      "errores_habituales": ["Olvidar sensores.", "Evaluar solo comodidad visual.", "No consultar limites de humedad."],
      "conceptos_relacionados": ["Humedad", "Niebla", "Sensores de vision", "Mantenimiento de posicion", "VLOS"],
      "referencia_al_bloque": "Bloque 4 A2 - Riesgos operacionales"
    },
    {
      "id": "B4-PRA-008",
      "titulo": "Calor extremo y rendimiento",
      "objetivo": "Valorar temperatura, bateria y refrigeracion en un escenario de inspeccion de panel solar.",
      "dificultad": "media",
      "tiempo_estimado": "30 min",
      "material_necesario": ["Escenario de panel solar", "Ficha de temperatura", "Plantilla de autonomia y limites"],
      "contexto": "La inspeccion de panel solar en calor extremo aparece como escenario real implicito del bloque.",
      "instrucciones_paso_a_paso": ["Describe las condiciones de calor.", "Identifica que rendimiento puede verse afectado.", "Relaciona calor con densidad del aire y refrigeracion de motores segun la fuente.", "Consulta los limites del fabricante simulados.", "Decide si falta informacion o si procede Go/No-Go."],
      "criterios_de_exito": ["El alumno considera temperatura como meteorologia operativa.", "Relaciona bateria y calor.", "No decide solo porque no hay viento."],
      "errores_habituales": ["Olvidar temperatura.", "Ignorar refrigeracion.", "No consultar manual."],
      "conceptos_relacionados": ["Temperatura", "Rendimiento de bateria", "Densidad del aire", "Refrigeracion de motores", "Limites del fabricante"],
      "referencia_al_bloque": "Bloque 4 A2 - Escenario panel solar"
    },
    {
      "id": "B4-PRA-009",
      "titulo": "Decision completa en plaza urbana",
      "objetivo": "Integrar viento local, topografia, VLOS, manual y Go/No-Go en un escenario unico.",
      "dificultad": "alta",
      "tiempo_estimado": "40 min",
      "material_necesario": ["Plano de plaza", "Datos actuales y prevision", "Ficha de manual", "Plantilla Go/No-Go"],
      "contexto": "Una plaza rodeada de edificios altos con viento cruzado puede producir efecto rotor y exige evaluacion meteorologica local.",
      "instrucciones_paso_a_paso": ["Marca edificios y posibles zonas de viento irregular.", "Separa prevision y condiciones actuales.", "Evalua VLOS.", "Compara viento, temperatura y humedad con el manual.", "Identifica factores variables.", "Redacta una decision Go/No-Go con justificacion."],
      "criterios_de_exito": ["El alumno integra varias dependencias.", "No decide con un solo dato.", "Justifica la decision con los conceptos del bloque."],
      "errores_habituales": ["Tratar la plaza como campo abierto.", "Ignorar rachas o microclima.", "No cruzar manual y VLOS."],
      "conceptos_relacionados": ["Efecto rotor", "Topografia", "VLOS", "Limites del fabricante", "Go/No-Go"],
      "referencia_al_bloque": "Bloque 4 A2 - Grafo de conocimiento y escenario real"
    },
    {
      "id": "B4-PRA-010",
      "titulo": "Auditoria de alcance meteorologico A2",
      "objetivo": "Clasificar contenido meteorologico como imprescindible, complementario o fuera de alcance.",
      "dificultad": "alta",
      "tiempo_estimado": "35 min",
      "material_necesario": ["Tarjetas de conceptos", "Tabla A/B/C", "Auditoria del bloque"],
      "contexto": "La auditoria separa turbulencia urbana, nubes y limites del fabricante de contenidos complementarios o fuera de alcance.",
      "instrucciones_paso_a_paso": ["Clasifica tarjetas como A, B o C.", "Coloca turbulencia urbana, nubes y limites del fabricante como imprescindibles.", "Coloca presion estatica/dinamica como complementario.", "Marca meteorologia de gran escala, frentes complejos y METAR/TAF como fuera de alcance.", "Explica por que no debes desarrollar el apartado C."],
      "criterios_de_exito": ["El alumno mantiene el alcance A2.", "Distingue imprescindible y complementario.", "No desarrolla METAR/TAF ni frentes complejos."],
      "errores_habituales": ["Abrir radiofonista.", "Convertir complementario en central.", "Desarrollar contenido fuera del alcance A2."],
      "conceptos_relacionados": ["Auditoria A/B/C", "Turbulencia urbana", "Formacion de nubes", "Limites del fabricante", "Fuera de alcance"],
      "referencia_al_bloque": "Bloque 4 A2 - Auditoria"
    }
  ]
}
;
