window.DRONLAB_A2_BLOQUE5_CASOS = {
  "curso": "DronLab A2",
  "bloque": "Bloque 5: Rendimiento de Vuelo del UAS",
  "titulo": "Casos practicos Bloque 5 A2",
  "total": 12,
  "distribucion": {"baja": 5, "media": 5, "alta": 2},
  "casos": [
    {
      "id": "B5-CASO-001",
      "titulo": "Camara adicional antes del despegue",
      "dificultad": "baja",
      "contexto": "Un piloto prepara un UAS C2 para una captura visual y quiere montar una camara adicional.",
      "situacion_inicial": "El dron enciende correctamente y la camara queda fijada, pero no se ha revisado el efecto de la carga util.",
      "informacion_disponible": ["La carga util conecta configuracion tecnica y rendimiento real.", "El piloto debe evaluar compatibilidad con MTOM.", "La carga puede afectar negativamente al Centro de Gravedad."],
      "problema_planteado": "Determinar que comprobaciones debe realizar el piloto antes de aceptar la configuracion.",
      "preguntas_para_el_alumno": ["Que debe comprobar respecto a la MTOM?", "Como puede afectar la camara al CG?", "Por que no basta con que el dron despegue?"],
      "objetivos_de_aprendizaje": ["Relacionar payload con MTOM.", "Relacionar payload con Centro de Gravedad.", "Evitar decisiones basadas solo en despegue correcto."],
      "errores_habituales": ["Comprobar solo que la camara esta sujeta.", "Olvidar que MTOM incluye aeronave y carga."],
      "conceptos_relacionados": ["Carga util", "MTOM", "Centro de Gravedad", "Rendimiento real"],
      "referencia_al_bloque": "Bloque 5 A2 - Conceptos puente"
    },
    {
      "id": "B5-CASO-002",
      "titulo": "Dron que cabecea de forma inesperada",
      "dificultad": "baja",
      "contexto": "Durante una comprobacion previa, el piloto observa que el UAS tiende a variar su actitud de forma poco estable.",
      "situacion_inicial": "Hay una carga instalada y el piloto no sabe si el problema se relaciona con ejes, CG o calibracion.",
      "informacion_disponible": ["Los ejes se cruzan en el CG.", "Un CG desplazado puede impedir el control.", "Sensores mal calibrados distorsionan la percepcion de los ejes."],
      "problema_planteado": "Identificar que conceptos deben revisarse antes de continuar.",
      "preguntas_para_el_alumno": ["Que eje se asocia al cabeceo?", "Que papel tiene el CG?", "Que sensores cita la fuente como ejemplo de calibracion?"],
      "objetivos_de_aprendizaje": ["Distinguir eje lateral y cabeceo.", "Conectar CG y estabilidad.", "Relacionar calibracion con ejes de rotacion."],
      "errores_habituales": ["Asociar cabeceo al eje vertical.", "Pensar que todo se corrige con mando."],
      "conceptos_relacionados": ["Eje lateral", "Cabeceo", "CG", "IMU", "Brujula"],
      "referencia_al_bloque": "Bloque 5 A2 - Ejes de vuelo y calibracion"
    },
    {
      "id": "B5-CASO-003",
      "titulo": "Operacion en dia de calor extremo",
      "dificultad": "baja",
      "contexto": "Se planifica una operacion A2 con un UAS C2 en una jornada de calor intenso.",
      "situacion_inicial": "La bateria esta cargada y no se detecta viento relevante, pero el piloto no ha valorado el efecto del calor.",
      "informacion_disponible": ["El calor extremo puede afectar a la densidad del aire.", "La densidad del aire afecta al rendimiento de las helices.", "Ignorar el calor extremo reduce el margen de potencia disponible."],
      "problema_planteado": "Valorar por que la ausencia de viento no basta para aceptar la operacion.",
      "preguntas_para_el_alumno": ["Que variable fisica cambia con el calor?", "A que afecta directamente la densidad del aire?", "Que error habitual aparece en este escenario?"],
      "objetivos_de_aprendizaje": ["Relacionar calor y densidad.", "Relacionar densidad y helices.", "Evitar analizar solo el viento."],
      "errores_habituales": ["Mirar solo viento.", "Usar autonomia nominal sin considerar condiciones."],
      "conceptos_relacionados": ["Densidad del aire", "Temperatura", "Helices", "Potencia disponible"],
      "referencia_al_bloque": "Bloque 5 A2 - Conceptos variables y riesgos"
    },
    {
      "id": "B5-CASO-004",
      "titulo": "Repaso de ejes antes de una maniobra",
      "dificultad": "baja",
      "contexto": "Un alumno debe explicar como se mueve el UAS en roll, pitch y yaw antes de practicar correcciones.",
      "situacion_inicial": "El alumno identifica los movimientos pero duda al asociarlos con los ejes.",
      "informacion_disponible": ["Eje longitudinal: alabeo/roll.", "Eje lateral/transversal: cabeceo/pitch.", "Eje vertical: guinada/yaw."],
      "problema_planteado": "Corregir la asociacion entre ejes y movimientos sin convertirlo en una lista memorizada sin aplicacion.",
      "preguntas_para_el_alumno": ["Que movimiento corresponde al eje longitudinal?", "Que movimiento corresponde al eje lateral?", "Cual es el error de examen citado?"],
      "objetivos_de_aprendizaje": ["Memorizar ejes correctamente.", "Evitar error tipico de examen.", "Aplicar ejes a maniobrabilidad."],
      "errores_habituales": ["Asociar cabeceo al eje vertical.", "Aprender nombres sin entender actitud."],
      "conceptos_relacionados": ["Ejes de vuelo", "Roll", "Pitch", "Yaw"],
      "referencia_al_bloque": "Bloque 5 A2 - Ejes de Vuelo y Rotacion"
    },
    {
      "id": "B5-CASO-005",
      "titulo": "Comprobacion de altura precisa",
      "dificultad": "baja",
      "contexto": "El piloto prepara una operacion donde necesita controlar con precision la altura del UAS.",
      "situacion_inicial": "La informacion de altura es relevante y el alumno debe decidir que dato critico del bloque debe recordar.",
      "informacion_disponible": ["El control de altura depende de asistencia barometrica.", "La asistencia barometrica es requerida para precision en altura.", "La altura maxima AGL indicada es 120 metros (400 ft)."],
      "problema_planteado": "Distinguir el dato de altura maxima y el requisito de asistencia barometrica.",
      "preguntas_para_el_alumno": ["Para que se requiere asistencia barometrica?", "Que altura maxima AGL aparece?", "Que error puede ocurrir si se mezclan ambos datos?"],
      "objetivos_de_aprendizaje": ["Fijar datos criticos.", "Relacionar sensores y altura.", "Evitar mezcla de unidades y requisitos."],
      "errores_habituales": ["Decir solo 120 sin AGL.", "No relacionar barometro con precision."],
      "conceptos_relacionados": ["Asistencia barometrica", "Altura AGL", "120 metros", "400 ft"],
      "referencia_al_bloque": "Bloque 5 A2 - Datos criticos"
    },
    {
      "id": "B5-CASO-006",
      "titulo": "Payload y autonomia real",
      "dificultad": "media",
      "contexto": "Una operacion requiere carga util adicional y el piloto estima autonomia usando el valor nominal.",
      "situacion_inicial": "La ruta prevista incluye viento enfrentado y el UAS lleva un sensor adicional.",
      "informacion_disponible": ["La autonomia varia segun peso de la carga util.", "La autonomia varia segun resistencia al viento enfrentada.", "Un CG desplazado puede agotar prematuramente baterias o motores."],
      "problema_planteado": "Evaluar por que la autonomia nominal puede no representar la autonomia real.",
      "preguntas_para_el_alumno": ["Que factores reducen autonomia real?", "Como se relaciona CG desplazado con consumo?", "Que informacion falta antes de aceptar la operacion?"],
      "objetivos_de_aprendizaje": ["Relacionar carga util y bateria.", "Relacionar viento enfrentado y autonomia.", "Identificar riesgos de CG desplazado."],
      "errores_habituales": ["Usar autonomia ideal.", "Ignorar resistencia al viento enfrentada."],
      "conceptos_relacionados": ["Autonomia", "Carga util", "Resistencia al viento", "CG"],
      "referencia_al_bloque": "Bloque 5 A2 - Conceptos variables"
    },
    {
      "id": "B5-CASO-007",
      "titulo": "Indice K elevado antes del vuelo",
      "dificultad": "media",
      "contexto": "Antes de una operacion, el piloto revisa condiciones relacionadas con posicionamiento.",
      "situacion_inicial": "El Indice K planetario aparece en un valor que obliga al piloto a valorar seguridad del posicionamiento.",
      "informacion_disponible": ["Indice K Planetario < 4 para operar con seguridad.", "Si el Indice K es >= 4 puede degradar sistemas de posicionamiento.", "El Indice K es un concepto variable del bloque."],
      "problema_planteado": "Interpretar el umbral y decidir que riesgo debe considerarse.",
      "preguntas_para_el_alumno": ["Que umbral indica la fuente?", "Que puede degradarse con actividad geomagnetica?", "Que error se evita al interpretar el signo del umbral?"],
      "objetivos_de_aprendizaje": ["Memorizar el umbral < 4.", "Relacionar Indice K y posicionamiento.", "Evitar invertir la condicion."],
      "errores_habituales": ["Invertir < 4 y >= 4.", "Ignorar variables no visibles."],
      "conceptos_relacionados": ["Indice K", "Posicionamiento", "Actividad geomagnetica", "Rendimiento"],
      "referencia_al_bloque": "Bloque 5 A2 - Datos criticos y variables"
    },
    {
      "id": "B5-CASO-008",
      "titulo": "Operacion a gran altitud",
      "dificultad": "media",
      "contexto": "El piloto prepara una operacion a gran altitud sobre el nivel del mar.",
      "situacion_inicial": "El UAS es el mismo que se usa en otras zonas, pero se anticipa menor rendimiento.",
      "informacion_disponible": ["La densidad del aire cambia con la altitud.", "La menor densidad afecta al rendimiento de las helices.", "La fuente cita perdida de rendimiento a gran altitud."],
      "problema_planteado": "Justificar por que el mismo UAS puede rendir de forma distinta.",
      "preguntas_para_el_alumno": ["Que variable cambia con la altitud?", "A que afecta la menor densidad?", "Que concepto inicial ayuda a entender la sustentacion?"],
      "objetivos_de_aprendizaje": ["Relacionar altitud y densidad.", "Aplicar rendimiento de helices.", "Conectar sustentacion y aire."],
      "errores_habituales": ["Pensar que la altitud no afecta a multirrotores.", "Responder solo bateria."],
      "conceptos_relacionados": ["Densidad del aire", "Altitud", "Helices", "Sustentacion"],
      "referencia_al_bloque": "Bloque 5 A2 - Escenarios reales implicitos"
    },
    {
      "id": "B5-CASO-009",
      "titulo": "Versiones incompatibles de RPS y dron",
      "dificultad": "media",
      "contexto": "Un piloto prepara la estacion de pilotaje remoto y el UAS antes de una sesion de vuelo.",
      "situacion_inicial": "Existe duda sobre si las versiones de software de la RPS y del dron son compatibles.",
      "informacion_disponible": ["La ingenieria plantea esta compatibilidad como pregunta nacida del bloque.", "La compatibilidad se relaciona con garantizar rendimiento de vuelo.", "Las ordenes de mando de la RPS intervienen en los ejes de vuelo."],
      "problema_planteado": "Determinar por que el rendimiento de vuelo no depende solo de la aeronave fisica.",
      "preguntas_para_el_alumno": ["Que elementos deben ser compatibles?", "Con que se relaciona esa compatibilidad?", "Como conecta la RPS con los ejes de vuelo?"],
      "objetivos_de_aprendizaje": ["Ver el UAS como sistema.", "Relacionar RPS y rendimiento.", "Evitar separar software de seguridad."],
      "errores_habituales": ["Pensar que software es secundario.", "Mirar solo motores o bateria."],
      "conceptos_relacionados": ["RPS", "Software compatible", "Ejes", "Rendimiento"],
      "referencia_al_bloque": "Bloque 5 A2 - Preguntas que nacen del bloque"
    },
    {
      "id": "B5-CASO-010",
      "titulo": "Vuelo de precision a baja altura",
      "dificultad": "media",
      "contexto": "Se plantea un vuelo de precision a baja altura cerca del suelo.",
      "situacion_inicial": "El piloto considera que volar bajo siempre sera mas estable y facil de controlar.",
      "informacion_disponible": ["La fuente cita efecto suelo como turbulencia propia del dron.", "El efecto suelo puede afectar la estabilidad.", "La estabilidad depende del CG y se relaciona con control en los tres ejes."],
      "problema_planteado": "Analizar por que baja altura no equivale automaticamente a operacion mas sencilla.",
      "preguntas_para_el_alumno": ["Que escenario cita la fuente?", "Que puede afectar el efecto suelo?", "Que otros conceptos de estabilidad se deben recordar?"],
      "objetivos_de_aprendizaje": ["Identificar efecto suelo.", "Relacionar baja altura y estabilidad.", "Conectar estabilidad con CG y ejes."],
      "errores_habituales": ["Pensar que cerca del suelo siempre es mas facil.", "Olvidar turbulencia propia del dron."],
      "conceptos_relacionados": ["Efecto suelo", "Baja altura", "Estabilidad", "CG"],
      "referencia_al_bloque": "Bloque 5 A2 - Escenarios reales implicitos"
    },
    {
      "id": "B5-CASO-011",
      "titulo": "Diagnostico de rendimiento deficiente",
      "dificultad": "alta",
      "contexto": "Durante una preparacion, el UAS muestra menor rendimiento del esperado.",
      "situacion_inicial": "Hay carga util, calor, posible viento enfrentado y dudas sobre calibracion de instrumentos.",
      "informacion_disponible": ["La carga util afecta MTOM y CG.", "La densidad del aire cambia con temperatura y humedad.", "La autonomia varia con carga y viento.", "Sensores mal calibrados distorsionan la percepcion de ejes."],
      "problema_planteado": "Construir una hipotesis ordenada sobre las causas sin inventar datos tecnicos.",
      "preguntas_para_el_alumno": ["Que factores deben comprobarse primero?", "Que conceptos afectan al rendimiento real?", "Que informacion no puede inventarse si no aparece en la fuente?"],
      "objetivos_de_aprendizaje": ["Integrar masa, aire, sensores y autonomia.", "Priorizar comprobaciones.", "Mantenerse dentro de la ingenieria disponible."],
      "errores_habituales": ["Culpar solo a la bateria.", "Inventar valores de fabricante o humedad."],
      "conceptos_relacionados": ["Rendimiento real", "Payload", "Densidad del aire", "Calibracion", "Autonomia"],
      "referencia_al_bloque": "Bloque 5 A2 - Grafo de conocimiento"
    },
    {
      "id": "B5-CASO-012",
      "titulo": "Auditoria de contenido fuera de alcance",
      "dificultad": "alta",
      "contexto": "Un material de apoyo mezcla rendimiento A2 con explicaciones avanzadas de BVLOS y centro de presiones de ala fija.",
      "situacion_inicial": "El profesor debe decidir que contenido conservar para el Bloque 5 y que marcar fuera del alcance.",
      "informacion_disponible": ["Imprescindible: ejes, CG, MTOM, fuerzas aerodinamicas y densidad del aire.", "Complementario: presion estatica/dinamica e impacto especifico de humedad.", "Fuera del alcance: BVLOS y centro de presiones avanzado para ala fija."],
      "problema_planteado": "Clasificar el material sin desarrollar contenidos fuera del A2.",
      "preguntas_para_el_alumno": ["Que debe conservarse como imprescindible?", "Que puede quedar como complementario?", "Que debe marcarse fuera del alcance?"],
      "objetivos_de_aprendizaje": ["Aplicar auditoria A/B/C.", "Evitar sobrecargar el bloque.", "Mantener el alcance A2."],
      "errores_habituales": ["Desarrollar BVLOS.", "Convertir presiones detalladas en eje principal."],
      "conceptos_relacionados": ["Auditoria", "Imprescindible", "Complementario", "Fuera del alcance"],
      "referencia_al_bloque": "Bloque 5 A2 - Auditoria"
    }
  ]
}

