window.DRONLAB_A2_BLOQUE2_CASOS = {
  "curso": "DronLab A2",
  "bloque": "Bloque 2: El Sistema UAS de Clase C2",
  "titulo": "Casos practicos Bloque 2 A2",
  "total": 12,
  "distribucion": {
    "baja": 5,
    "media": 5,
    "alta": 2
  },
  "casos": [
    {
      "id": "B2-CASO-001",
      "titulo": "Ficha tecnica incompleta",
      "dificultad": "baja",
      "contexto": "Un alumno revisa un UAS que el vendedor presenta como apto para trabajar en A2.",
      "situacion_inicial": "La ficha indica que la aeronave pesa menos de 4 kg, pero el alumno no localiza la etiqueta fisica de clase C2 ni el numero de serie unico.",
      "informacion_disponible": ["Un UAS C2 requiere MTOM inferior a 4 kg.", "La clase C2 depende de etiqueta fisica de clase C2.", "La fuente cita numero de serie unico y alimentacion electrica como dependencias basicas."],
      "problema_planteado": "Determinar si basta con que el UAS pese menos de 4 kg para considerarlo C2.",
      "preguntas_para_el_alumno": ["Que evidencias faltan para verificar la clase C2?", "Por que no basta el peso?", "Que dato identifica de forma unica la aeronave?"],
      "objetivos_de_aprendizaje": ["Distinguir masa, marcado y numero de serie.", "Evitar validar C2 solo por apariencia o ficha comercial.", "Aplicar una comprobacion documental y fisica basica."],
      "errores_habituales": ["Fiarse solo del nombre comercial.", "Considerar suficiente que el UAS pese menos de 4 kg."],
      "conceptos_relacionados": ["UAS de Clase C2", "MTOM inferior a 4 kg", "Etiqueta fisica C2", "Numero de serie unico"],
      "referencia_al_bloque": "Bloque 2 A2 - Definicion y dependencias C2"
    },
    {
      "id": "B2-CASO-002",
      "titulo": "Accesorios y MTOM",
      "dificultad": "baja",
      "contexto": "Un piloto quiere anadir accesorios a su UAS de clase C2 antes de una operacion.",
      "situacion_inicial": "El piloto sabe que la clase C2 tiene MTOM inferior a 4 kg, pero no ha comprobado si los accesorios afectan al conjunto en despegue.",
      "informacion_disponible": ["La MTOM de clase C2 es inferior a 4 kg.", "La ingenieria plantea si es legal modificar fisicamente un UAS C2 anadiendo accesorios que superen su MTOM original.", "Las instrucciones del fabricante ayudan a verificar limites de peso."],
      "problema_planteado": "Valorar que debe comprobarse antes de operar con accesorios instalados.",
      "preguntas_para_el_alumno": ["Que dato de masa debe respetarse?", "Que documento o referencia ayuda a verificar limites?", "Que riesgo aparece si se supera la MTOM original?"],
      "objetivos_de_aprendizaje": ["Aplicar el limite MTOM.", "Relacionar accesorios con configuracion real del UAS.", "Usar instrucciones del fabricante como puente operativo."],
      "errores_habituales": ["Pensar que los accesorios no cuentan.", "Memorizar < 4 kg sin aplicarlo al UAS configurado."],
      "conceptos_relacionados": ["MTOM", "Instrucciones del fabricante", "Componentes amovibles"],
      "referencia_al_bloque": "Bloque 2 A2 - MTOM e instrucciones del fabricante"
    },
    {
      "id": "B2-CASO-003",
      "titulo": "Fachada con peaton en acera",
      "dificultad": "baja",
      "contexto": "Un piloto realiza una inspeccion de fachada con un UAS C2.",
      "situacion_inicial": "Durante la inspeccion aparece un peaton en la acera y el piloto quiere mantener la separacion reducida indicada en la ingenieria.",
      "informacion_disponible": ["La clase C2 permite reducir distancias hasta 5 metros segun la fuente.", "El vuelo a 5 metros depende del modo de baja velocidad.", "El modo de baja velocidad limita la velocidad de avance a 3 m/s."],
      "problema_planteado": "Decidir que funcion C2 debe gestionar el piloto antes de acercarse.",
      "preguntas_para_el_alumno": ["Que condicion desbloquea la distancia de 5 m?", "Que velocidad maxima debe recordar?", "Por que no puede aplicar 5 m como regla aislada?"],
      "objetivos_de_aprendizaje": ["Relacionar distancia reducida con modo lento.", "Aplicar el dato de 3 m/s.", "Justificar una decision operativa en escenario real."],
      "errores_habituales": ["Acercarse sin activar modo lento.", "Recordar 5 m y olvidar 3 m/s."],
      "conceptos_relacionados": ["Modo de baja velocidad", "Vuelo a 5 metros", "Mitigacion de danos"],
      "referencia_al_bloque": "Bloque 2 A2 - Modo de baja velocidad y vuelo a 5 m"
    },
    {
      "id": "B2-CASO-004",
      "titulo": "Modo lento asumido como automatico",
      "dificultad": "baja",
      "contexto": "Durante una preparacion previa, un alumno afirma que el UAS activara el modo lento por si solo cuando haya personas cerca.",
      "situacion_inicial": "El alumno no comprueba en la estacion de control si el modo de baja velocidad esta seleccionado.",
      "informacion_disponible": ["El modo de baja velocidad es seleccionable desde la estacion de control.", "La activacion es manual por el piloto a distancia, excepto en ala fija donde no aplica esta reduccion.", "El modo lento reduce energia de impacto y aumenta tiempo de reaccion."],
      "problema_planteado": "Identificar el error de interpretacion sobre la activacion del modo lento.",
      "preguntas_para_el_alumno": ["Quien debe activar el modo lento?", "Desde donde se selecciona?", "Que riesgo genera asumir que siempre se activa solo?"],
      "objetivos_de_aprendizaje": ["Comprender la responsabilidad del piloto.", "Distinguir funcion seleccionable y automatismo supuesto.", "Reforzar la comprobacion previa."],
      "errores_habituales": ["Suponer activacion automatica.", "No comprobar la estacion de control."],
      "conceptos_relacionados": ["Modo de baja velocidad", "Estacion de control", "Activacion manual"],
      "referencia_al_bloque": "Bloque 2 A2 - Activacion del modo de baja velocidad"
    },
    {
      "id": "B2-CASO-005",
      "titulo": "DRI con numero equivocado",
      "dificultad": "media",
      "contexto": "Un piloto configura la identificacion a distancia directa antes de un vuelo.",
      "situacion_inicial": "Al introducir los datos, carga el identificador de piloto ESP-RP porque cree que todos los numeros AESA son equivalentes.",
      "informacion_disponible": ["La DRI depende de la carga previa del numero de registro de operador obtenido en la sede electronica de AESA.", "La DRI emite identificacion del operador, numero de serie, posicion, altura, trayectoria y velocidad.", "Confundir ESP-RP con numero de operador es un error operacional citado."],
      "problema_planteado": "Detectar el error de configuracion y justificar que numero corresponde cargar.",
      "preguntas_para_el_alumno": ["Que numero debe cargarse en DRI?", "Por que ESP-RP no resuelve este caso?", "Que datos emite DRI durante el vuelo?"],
      "objetivos_de_aprendizaje": ["Distinguir numero de operador e identificacion de piloto.", "Aplicar dependencias de DRI.", "Evitar una configuracion que invalide la operacion."],
      "errores_habituales": ["Cargar ESP-RP en DRI.", "No verificar la configuracion antes de despegar."],
      "conceptos_relacionados": ["DRI", "Numero de operador AESA", "ESP-RP", "Legalidad de la operacion"],
      "referencia_al_bloque": "Bloque 2 A2 - DRI y numero de operador"
    },
    {
      "id": "B2-CASO-006",
      "titulo": "Geoconsciencia sin datos actualizados",
      "dificultad": "media",
      "contexto": "Un piloto confia en que la geoconsciencia del UAS le avisara de cualquier zona restringida.",
      "situacion_inicial": "No revisa si la base de datos geografica esta actualizada antes del vuelo.",
      "informacion_disponible": ["La geoconsciencia avisa al aproximarse a limites de zonas UAS restringidas o prohibidas.", "Depende de la actualizacion de datos geograficos proporcionados por autoridades.", "ENAIRE Drones aparece como ejemplo de fuente de datos."],
      "problema_planteado": "Determinar por que la geoconsciencia no debe tratarse como sustituto de revision previa.",
      "preguntas_para_el_alumno": ["Que hace la geoconsciencia?", "De que depende para ser util?", "Que error evita comprender que avisa pero no autoriza?"],
      "objetivos_de_aprendizaje": ["Distinguir aviso tecnico y autorizacion.", "Reconocer datos geograficos como variable.", "Incorporar actualizacion a la preparacion previa."],
      "errores_habituales": ["Operar con bases de datos antiguas.", "Creer que el aviso concede permiso."],
      "conceptos_relacionados": ["Geoconsciencia", "Datos geograficos actualizados", "Zonas restringidas o prohibidas"],
      "referencia_al_bloque": "Bloque 2 A2 - Geoconsciencia"
    },
    {
      "id": "B2-CASO-007",
      "titulo": "Enlace C2 no verificado",
      "dificultad": "media",
      "contexto": "El piloto prepara el despegue de un UAS C2 tras encender aeronave y RPS.",
      "situacion_inicial": "Da por hecho que la comunicacion es correcta porque ambos equipos parecen encendidos.",
      "informacion_disponible": ["El enlace de mando y control conecta la RPS con la aeronave.", "La clase C2 exige enlace protegido contra accesos no autorizados.", "Debe disponer de metodos de recuperacion ante perdida y verificarse antes del despegue."],
      "problema_planteado": "Identificar que comprobacion operacional falta antes del despegue.",
      "preguntas_para_el_alumno": ["Que conecta el enlace C2?", "Que dos cualidades exige la clase C2 al enlace?", "Que riesgo operativo aparece si no se verifica?"],
      "objetivos_de_aprendizaje": ["Comprender el enlace C2 como concepto puente.", "Relacionar proteccion y recuperacion.", "Aplicar checklist previo al despegue."],
      "errores_habituales": ["No verificar el enlace antes de despegar.", "Pensar que comunicar equivale a estar protegido."],
      "conceptos_relacionados": ["Enlace de mando y control", "RPS", "Aeronave", "Recuperacion ante perdida"],
      "referencia_al_bloque": "Bloque 2 A2 - Enlace de mando y control C2"
    },
    {
      "id": "B2-CASO-008",
      "titulo": "Bateria con margen insuficiente",
      "dificultad": "media",
      "contexto": "Un piloto planifica una operacion a cierta distancia del punto de aterrizaje.",
      "situacion_inicial": "Mantiene el mismo margen de aviso de bateria que en vuelos cortos y cercanos.",
      "informacion_disponible": ["Los avisos de bateria dependen de sensores del UAS y RPS.", "Desbloquean gestion de autonomia y RTH seguro.", "El margen de aviso de bateria es ajustable segun resistencia y distancia de la operacion."],
      "problema_planteado": "Valorar si el margen de aviso debe adaptarse a la operacion prevista.",
      "preguntas_para_el_alumno": ["Que sistemas intervienen en los avisos de bateria?", "Por que el margen es variable?", "Que decision permite un aviso con margen suficiente?"],
      "objetivos_de_aprendizaje": ["Relacionar distancia y margen de bateria.", "Distinguir aviso temprano y aviso critico.", "Tomar decisiones de autonomia antes de perder margen."],
      "errores_habituales": ["Usar siempre el mismo margen.", "Ignorar avisos hasta que sean urgentes."],
      "conceptos_relacionados": ["Avisos de bateria", "UAS y RPS", "RTH seguro", "Margen ajustable"],
      "referencia_al_bloque": "Bloque 2 A2 - Avisos de bateria"
    },
    {
      "id": "B2-CASO-009",
      "titulo": "Software de RPS y aeronave no coincidente",
      "dificultad": "media",
      "contexto": "Durante el pre-vuelo, el piloto detecta que la estacion de pilotaje y la aeronave no tienen software coincidente.",
      "situacion_inicial": "El piloto ha actualizado el dron, pero no ha revisado la RPS.",
      "informacion_disponible": ["La version de software o firmware debe ser la ultima publicada por el fabricante.", "Debe estar actualizada tanto en aeronave como en RPS.", "La discrepancia puede impedir el despegue por seguridad segun el escenario implicito."],
      "problema_planteado": "Decidir que parte del sistema debe revisarse antes de continuar.",
      "preguntas_para_el_alumno": ["Donde debe estar actualizado el software?", "Que escenario de fallo aparece en la ingenieria?", "Por que actualizar solo el dron puede no bastar?"],
      "objetivos_de_aprendizaje": ["Entender UAS como sistema completo.", "Aplicar la revision de firmware a aeronave y RPS.", "Reconocer software como concepto variable."],
      "errores_habituales": ["Actualizar solo una parte del sistema.", "Intentar despegar sin resolver la discrepancia."],
      "conceptos_relacionados": ["Software", "Firmware", "RPS", "Aeronave", "Ultima version del fabricante"],
      "referencia_al_bloque": "Bloque 2 A2 - Software y firmware"
    },
    {
      "id": "B2-CASO-010",
      "titulo": "Helices y camara sin asegurar",
      "dificultad": "baja",
      "contexto": "Antes de una practica de comprobacion del sistema, el alumno centra toda la revision en pantalla y configuraciones.",
      "situacion_inicial": "No revisa fisicamente helices ni camara porque considera que el sistema C2 es principalmente software.",
      "informacion_disponible": ["La fuente cita como error habitual no asegurar correctamente componentes amovibles.", "Los ejemplos citados son helices y camaras.", "La seguridad C2 combina requisitos fisicos y digitales."],
      "problema_planteado": "Identificar que parte de la revision del sistema se esta omitiendo.",
      "preguntas_para_el_alumno": ["Que componentes cita la fuente?", "Por que no basta revisar software?", "Que riesgo habitual se esta produciendo?"],
      "objetivos_de_aprendizaje": ["Reconocer componentes amovibles.", "Integrar revision fisica y digital.", "Evitar errores de preparacion prevuelo."],
      "errores_habituales": ["Olvidar helices o camaras.", "Centrarse solo en pantallas."],
      "conceptos_relacionados": ["Componentes amovibles", "Helices", "Camaras", "Inspeccion fisica"],
      "referencia_al_bloque": "Bloque 2 A2 - Componentes amovibles"
    },
    {
      "id": "B2-CASO-011",
      "titulo": "Pregunta de examen con masas de clase",
      "dificultad": "alta",
      "contexto": "En un repaso, el profesor plantea una pregunta sobre la MTOM de C2 mezclando datos de otras clases.",
      "situacion_inicial": "El alumno duda entre 900 g, menos de 4 kg y 25 kg porque recuerda numeros, pero no los asocia bien.",
      "informacion_disponible": ["La MTOM de clase C2 es inferior a 4 kg.", "El error de examen citado es confundir C2 con C1 de 900 g o C3 de 25 kg.", "C1 y C3 solo aparecen como contraste de error."],
      "problema_planteado": "Resolver la confusion sin desarrollar otras clases fuera del alcance del bloque.",
      "preguntas_para_el_alumno": ["Que dato pertenece a C2?", "Por que aparecen 900 g y 25 kg?", "Como evitarias estudiar C1 y C3 mas alla del contraste?"],
      "objetivos_de_aprendizaje": ["Asociar correctamente clase y masa.", "Evitar expansion fuera de alcance.", "Preparar una respuesta de examen no ambigua."],
      "errores_habituales": ["Responder 900 g o 25 kg para C2.", "Desarrollar clases no necesarias para el bloque."],
      "conceptos_relacionados": ["MTOM C2", "Errores de examen", "C1 y C3 como contraste"],
      "referencia_al_bloque": "Bloque 2 A2 - Errores de examen"
    },
    {
      "id": "B2-CASO-012",
      "titulo": "Deriva hacia STS-ES",
      "dificultad": "alta",
      "contexto": "En clase surge una pregunta sobre Escenarios Estandar Nacionales y requisitos especificos de aeronave.",
      "situacion_inicial": "Un alumno quiere comparar C2 con STS-ES-02NE de menos de 25 kg y pide desarrollar esa operacion.",
      "informacion_disponible": ["La auditoria clasifica STS-ES y sus requisitos especificos de aeronave como fuera del alcance del A2.", "El contenido imprescindible del Bloque 2 es definicion C2, modo lento, geoconsciencia, Remote ID y aviso de bateria.", "Lo fuera de alcance no debe desarrollarse."],
      "problema_planteado": "Decidir como responder sin romper el alcance del Bloque 2 A2.",
      "preguntas_para_el_alumno": ["Como se clasifica STS-ES en este bloque?", "Que contenidos imprescindibles deben mantenerse?", "Que frase permite reconducir sin desarrollar contenido fuera de alcance?"],
      "objetivos_de_aprendizaje": ["Aplicar auditoria de alcance.", "Evitar mezclar A2 con STS-ES.", "Centrar el bloque en el sistema UAS C2."],
      "errores_habituales": ["Desarrollar STS-ES por curiosidad.", "Convertir contenido fuera de alcance en eje de clase."],
      "conceptos_relacionados": ["Auditoria de alcance", "Fuera del alcance A2", "STS-ES", "Contenidos imprescindibles"],
      "referencia_al_bloque": "Bloque 2 A2 - Alcance y cierre"
    }
  ]
}
;
