window.DRONLAB_A2_BLOQUE5_CHULETAS = {
  "curso": "DronLab A2",
  "bloque": "Bloque 5: Rendimiento de Vuelo del UAS",
  "titulo": "Chuletas Bloque 5 A2",
  "chuletas": [
    {"id":"B5-CH-001","titulo":"Resumen del Bloque 5","tipo":"resumen","items":["El rendimiento depende de fisica, masa, aire, sensores y configuracion.","Las cuatro fuerzas son sustentacion, peso, empuje y resistencia.","Los tres ejes se cruzan en el Centro de Gravedad.","La carga util debe comprobarse frente a MTOM y CG.","La densidad del aire cambia con altitud, temperatura y humedad.","La calibracion y la compatibilidad RPS-dron afectan al rendimiento."]},
    {"id":"B5-CH-002","titulo":"Flujo de rendimiento","tipo":"flujo","items":["Identificar fuerzas de vuelo","Ubicar ejes y Centro de Gravedad","Revisar carga util y MTOM","Evaluar densidad del aire","Comprobar calibracion e instrumentos","Aplicar datos criticos antes de operar"]},
    {"id":"B5-CH-003","titulo":"Ejes y Centro de Gravedad","tipo":"esquema","items":["Eje longitudinal: alabeo / roll.","Eje lateral o transversal: cabeceo / pitch.","Eje vertical: guinada / yaw.","Los tres ejes se cruzan en el CG.","El CG es el punto imaginario donde se concentra la masa.","Un CG desplazado compromete control y estabilidad."]},
    {"id":"B5-CH-004","titulo":"MTOM, payload y autonomia","tipo":"flujo","items":["MTOM incluye aeronave mas carga.","MTOM no debe superarse nunca.","Clase C2: < 4 kg.","Payload conecta configuracion tecnica y rendimiento real.","Payload puede afectar negativamente al CG.","Autonomia varia con carga util y resistencia al viento enfrentada."]},
    {"id":"B5-CH-005","titulo":"Datos criticos","tipo":"tabla","items":[{"dato":"Masa Maxima C2","valor":"< 4 kg","uso":"Legalidad y seguridad estructural"},{"dato":"Altura Maxima AGL","valor":"120 metros (400 ft)","uso":"Dato critico de operacion"},{"dato":"Indice K Planetario","valor":"< 4","uso":"Operar con seguridad segun posicionamiento"},{"dato":"Asistencia Barometrica","valor":"Requerida","uso":"Precision en altura"},{"dato":"Umbral de aprobado","valor":"75% de aciertos","uso":"Referencia de examen"},{"dato":"Densidad del aire","valor":"Variable","uso":"Rendimiento de helices"},{"dato":"Calibracion","valor":"IMU y brujula","uso":"Percepcion de ejes y estabilidad"},{"dato":"CG","valor":"Dentro de limites","uso":"Control seguro en tres ejes"}]},
    {"id":"B5-CH-006","titulo":"Errores habituales","tipo":"tabla","items":[{"error":"Reducir rendimiento a bateria","evita":"Revisar masa, aire, sensores y configuracion."},{"error":"Confundir ejes","evita":"Asociar roll, pitch y yaw al eje correcto."},{"error":"Cabeceo en eje vertical","evita":"Recordar pitch = eje lateral/transversal."},{"error":"Payload solo pesa","evita":"Revisar MTOM y CG."},{"error":"MTOM como recomendacion","evita":"Tratarla como limite que no se supera."},{"error":"Ignorar calor extremo","evita":"Relacionar temperatura con densidad y potencia disponible."},{"error":"Autonomia nominal fija","evita":"Considerar carga util y viento enfrentado."},{"error":"Desarrollar BVLOS","evita":"Marcar fuera del alcance del curso A2."}]},
    {"id":"B5-CH-007","titulo":"Checklist final","tipo":"checklist","items":["Cuatro fuerzas identificadas.","Ejes roll, pitch y yaw asociados correctamente.","Centro de Gravedad revisado.","Carga util comprobada frente a MTOM.","Masa Maxima C2 < 4 kg recordada.","Altura Maxima AGL 120 metros (400 ft) recordada.","Densidad del aire valorada por altitud, temperatura y humedad.","Calibracion de IMU y brujula considerada.","Indice K Planetario < 4 comprobado si aplica.","Autonomia valorada segun carga util y viento enfrentado."]}
  ]
}

