window.DRONLAB_A2_BLOQUE6_CHULETAS = {
  "curso": "DronLab A2",
  "bloque": "Bloque 6: Atenuaciones tecnicas y operacionales",
  "titulo": "Chuletas Bloque 6 A2",
  "chuletas": [
    {"id":"B6-CH-001","titulo":"Resumen del Bloque 6","tipo":"resumen","items":["La mitigacion A2 combina sistema, piloto, entorno y datos criticos.","Las atenuaciones tecnicas son funciones o dispositivos integrados en el UAS C2.","Las atenuaciones operacionales son procedimientos y maniobras del piloto.","El modo lento permite pasar de 30 m a 5 m.","La evaluacion del lugar identifica personas, obstaculos y zonas de prevencion.","La recuperacion manual evita depender exclusivamente de automatismos."]},
    {"id":"B6-CH-002","titulo":"Flujo de mitigacion","tipo":"flujo","items":["Identificar personas no participantes y obstaculos","Seleccionar atenuaciones tecnicas","Aplicar atenuaciones operacionales","Usar distancias 30m/5m y Regla 1:1","Contener con geoconsciencia/geofencing","Gestionar incursiones y recuperacion manual"]},
    {"id":"B6-CH-003","titulo":"Tecnica vs operacional","tipo":"esquema","items":["Tecnica: integrada en el UAS C2.","Tecnica: limita altura, velocidad o energia.","Tecnica: depende de marcado C2 y software configurado.","Operacional: procedimiento o maniobra del piloto.","Operacional: mantiene margenes dinamicos observando el entorno.","Error de examen: confundir hardware/software con maniobras/distancias."]},
    {"id":"B6-CH-004","titulo":"Modo lento y distancias","tipo":"flujo","items":["Distancia normal A2: >= 30 m.","Modo de baja velocidad: puente C2-distancias.","Distancia en modo lento: >= 5 m.","Velocidad maxima modo lento: <= 3 m/s.","Vuelo a 5 m depende del modo lento.","No usar 5 m como regla general."]},
    {"id":"B6-CH-005","titulo":"Tabla de datos criticos","tipo":"tabla","items":[{"dato":"Distancia A2 normal","valor":">= 30 m","uso":"Referencia general"},{"dato":"Distancia modo lento","valor":">= 5 m","uso":"Distancia reducida"},{"dato":"Velocidad modo lento","valor":"<= 3 m/s","uso":"Condicion tecnica"},{"dato":"Regla 1:1","valor":"Altura <= distancia horizontal","uso":"Altura proporcional"},{"dato":"Altura general","valor":"120 m AGL","uso":"Limitacion de altura"},{"dato":"Examen A2","valor":"75%","uso":"Umbral de aprobado"},{"dato":"Concentraciones","valor":"Nunca","uso":"Categoria abierta"},{"dato":"Volumen operacional","valor":"Variable","uso":"Mision, topografia y objetivos"}]},
    {"id":"B6-CH-006","titulo":"Errores habituales","tipo":"tabla","items":[{"error":"Confiar solo en automaticos","evita":"Preparar recuperacion manual."},{"error":"Confundir tecnica y operacional","evita":"Separar sistema y piloto."},{"error":"Aplicar 5 m sin modo lento","evita":"Comprobar <= 3 m/s."},{"error":"Datos geograficos obsoletos","evita":"Actualizar geoconsciencia."},{"error":"Volumen operacional fijo","evita":"Adaptar a cada mision."},{"error":"No observar terceros","evita":"Mantener margenes dinamicos."},{"error":"Terminacion sin comprobar","evita":"Comprobar antes del despegue."},{"error":"Desarrollar SORA/EAS","evita":"Marcar fuera del alcance A2."}]},
    {"id":"B6-CH-007","titulo":"Checklist final","tipo":"checklist","items":["Personas no participantes identificadas.","Obstaculos y zonas de prevencion marcados.","Volumen operacional adaptado a mision, topografia y objetivos.","Modo lento configurado si se plantea 5 m.","Velocidad <= 3 m/s recordada.","Regla 1:1 aplicada.","Geoconsciencia/geofencing revisados.","Datos geograficos actualizados.","Sistema de terminacion comprobado antes del despegue.","Recuperacion manual preparada ante fallo de automaticos."]}
  ]
}

